### ISSUE TITLE
Uncaught TypeError: Cannot read property 'url' of null

### ISSUE THREAD

**Issue by Arcanemagus** [atom/github#1026]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When switching branches to `master` this error popped up in Atom.

### Steps to Reproduce

1. Unknown, possibly switching branches in an external application?

**Expected behavior:**

No error

**Actual behavior:**

Uncaught TypeError: Cannot read property 'url' of null

Stack Trace:
```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\fbjs\lib\resolveImmediate.js:27

TypeError: Cannot read property 'url' of null
    at PrInfo.render (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/github/lib/containers/pr-info-container.js:115:67)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:798:36)
    at ReactCompositeComponentWrapper._renderValidatedComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:821:38)
    at ReactCompositeComponentWrapper.performInitialMount (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:361:36)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:257:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:45:41)
    at ReactCompositeComponentWrapper.performInitialMount (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:370:40)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:257:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:45:41)
    at ReactDOMComponent.mountChildren (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:236:50)
    at ReactDOMComponent._createInitialChildren (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:703:38)
    at ReactDOMComponent.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:522:18)
    at Object.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:45:41)
    at ReactDOMComponent.mountChildren (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:236:50)
    at ReactDOMComponent._createInitialChildren (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:703:38)
    at ReactDOMComponent.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:522:18)
    at Object.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:45:41)
    at ReactCompositeComponentWrapper.performInitialMount (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:370:40)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:257:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:45:41)
    at ReactCompositeComponentWrapper.performInitialMount (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:370:40)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:257:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:45:41)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:764:46)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:723:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:644:18)
    at ReactCompositeComponentWrapper.receiveComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:546:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:124:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:753:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:723:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:644:18)
    at ReactCompositeComponentWrapper.receiveComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:546:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:124:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:753:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:723:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:644:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:560:18)
    at Object.performUpdateIfNecessary (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactReconciler.js:156:28)
    at runBatchedUpdates (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactUpdates.js:150:27)
    at ReactReconcileTransaction.perform (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at ReactUpdatesFlushTransaction.perform (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at ReactUpdatesFlushTransaction.perform (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactUpdates.js:89:38)
    at Object.flushBatchedUpdates (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactUpdates.js:172:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/Transaction.js:209:31)
    at ReactDefaultBatchingStrategyTransaction.perform (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/Transaction.js:156:22)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.enqueueUpdate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactUpdates.js:200:28)
    at enqueueUpdate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:24:22)
    at Object.enqueueSetState (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:218:11)
    at RelayRenderer.ReactComponent.setState (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react/lib/ReactBaseClasses.js:64:22)
    at RelayReadyState.onReadyStateChange [as _onReadyStateChange] (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-relay/lib/RelayRenderer.js:152:20)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/react-relay/lib/RelayReadyState.js:73:19
    at tryCallOne (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/promise/lib/core.js:37:18)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/promise/lib/core.js:123:21
    at flush (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/asap/raw.js:50:35)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Reproduces how often:**

Unknown, must be extremely rare as I only just saw this for the first time.

### Versions

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Additional Information

<details>
<summary>Package list and Commands</summary>

### Commands

```
     -3:19.4.0 intentions:highlight (input.hidden-input)
     -3:19 core:save (input.hidden-input)
     -3:07.7.0 core:backspace (input.hidden-input)
     -3:07.1.0 core:move-right (input.hidden-input)
     -3:06.7.0 core:delete (input.hidden-input)
     -3:06.0 intentions:highlight (input.hidden-input)
     -3:05.7.0 core:save (input.hidden-input)
     -2:45.5.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -2:43.3.0 intentions:highlight (input.hidden-input)
     -2:43 core:save (input.hidden-input)
     -1:56.7.0 core:delete (input.hidden-input)
  2x -1:56.4.0 intentions:highlight (input.hidden-input)
     -1:55.8.0 core:save (input.hidden-input)
     -0:29.2.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -0:27.2.0 intentions:highlight (input.hidden-input)
     -0:26.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6
atom-beautify 0.30.3
atom-jade 0.3.0
atom-material-syntax 1.0.6
atom-material-syntax-dark 1.0.0
atom-material-syntax-light 0.4.6
atom-material-ui 2.0.4
atom-typescript 11.0.6
autocomplete-lua 0.8.2
autocomplete-python 1.9.1
busy-signal 1.4.3
docblockr 0.10.5
editorconfig 2.2.2
file-watcher 1.1.0
fizzy 0.21.0
flow-ide 1.6.0
highlight-selected 0.13.1
hyperclick 0.1.2
intentions 1.1.2
language-ansible 0.2.1
language-babel 2.66.1
language-chef 0.10.0
language-cjson 0.0.1
language-docker 1.1.8
language-elixir 0.19.0
language-erlang 3.2.0
language-fortran 2.1.0
language-gettext 0.6.1
language-glsl 2.0.1
language-haml 0.25.0
language-haskell 1.12.1
language-icinga2 0.3.0
language-ini 1.19.0
language-jade 0.7.2
language-jolie 0.5.0
language-kotlin 0.5.0
language-lua 0.9.11
language-moonscript 1.7.1
language-postcss 1.3.1
language-powershell 4.0.0
language-puppet 0.22.0
language-r 0.4.1
language-reg 0.0.0
language-rust 0.4.11
language-swift 0.5.0
language-terraform 0.8.1
language-vue 0.23.0
linter 2.2.0
linter-alex 4.0.0
linter-clang 4.1.1
linter-coffeelint 1.2.1
linter-csslint 1.3.4
linter-eslint 8.2.1
linter-flake8 2.2.1
linter-htmlhint 1.3.3
linter-js-standard 3.9.1
linter-js-yaml 1.2.7
linter-jshint 3.1.5
linter-jsonlint 1.3.0
linter-markdown 4.0.1
linter-perl 0.8.1
linter-perlcritic 1.4.2
linter-php 1.3.2
linter-phpcs 1.6.7
linter-phpmd 1.5.3
linter-proselint 3.2.1
linter-pylama 0.9.3
linter-pylint 2.1.0
linter-rails-best-practices 0.2.2
linter-reek 2.2.1
linter-rubocop 2.1.1
linter-ruby 1.2.5
linter-stylelint 3.11.0
linter-tidy 2.3.1
linter-ui-default 1.6.2
linter-ui-plus 0.3.2
mapfile-grammar 0.1.0
merge-conflicts 1.4.5
minimap-git-diff 4.3.1
minimap-highlight-selected 4.6.1
minimap-linter 2.0.0
minimap-plus 4.29.2
minimap-selection 4.4.0
monokai 0.24.0
nord-atom-syntax 0.9.1
nord-atom-ui 0.11.0
pigments 0.39.1
sequential-number 0.5.0
seti-syntax 1.1.3
seti-ui 1.9.0
sort-lines 0.14.0
Stylus 3.1.1
svn 0.0.13
tab-control 0.6.10
toggle-quotes 1.0.1
trailing-spaces 0.4.0
```
</details>

**Comment by rafaelmagu** [comment]
To add to the list, I get this issue on macOS Sierra when trying to load the `GitHub (preview)` tab, and it happens 100% of the time, regardless of branch I'm working on.

**Comment by ganoch** [comment]
Same error on GitHub tab, was ok at first. Then I chose something on the list of pull requests of [Deprecation Detector](https://github.com/sensiolabs-de/deprecation-detector) project. From then on this error is always displayed.
