### ISSUE TITLE
Uncaught Error: Object has been destroyedError: Object has been destroyed    at Error (native)...

### ISSUE THREAD

**Issue by abuammar** [atom/github#1038]
[Enter steps to reproduce:]

1. ... when ever click file on tab in atom editor this window pops up stating 

Uncaught Error: Object has been destroyed Error: Object has been destroyed at Error (native) at EventEmitter. (/Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:326:54) at emitThree (events.js:116:13) at EventEmitter.emit (events.js:194:7) at WebContents. (/Users/ws1/Downloads/Atom.app/Contents/Resource

2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: Object has been destroyed
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.<anonymous> (/Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:326:54)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217

Error: Object has been destroyed
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.<anonymous> (/Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:326:54)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.descriptor.get [as webContents] (/Users/ws1/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:131:16)
    at EventEmitter.handleMessages (/Users/ws1/Downloads/Atom.app/Contents/Resources/app/node_modules/github/lib/worker-manager.js:421:49)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -6:14.5.0 core:backspace (input.hidden-input)
     -6:13.5.0 core:save (input.hidden-input)
     -4:03.8.0 core:undo (input.hidden-input)
     -4:02.8.0 core:save (input.hidden-input)
  4x -1:16.3.0 core:backspace (input.hidden-input)
     -1:10 autocomplete-plus:confirm (input.hidden-input)
     -1:09.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
nuclide 0.165.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, is reproducible in safe mode (atom --safe)?

> ... when ever click file on tab in atom editor this window pops up stating

Can you share a screencast or screenshots of the behavior you're seeing?

**Comment by abuammar** [comment]
the error is reproducible and not in safe mode

**Comment by abuammar** [comment]
![screen shot 2017-07-26 at 10 49 50 am](https://user-images.githubusercontent.com/3853082/28610224-3ef51c46-71f0-11e7-9ef9-eec1a4c443f1.png)
this is the error message

**Comment by rsese** [comment]
> the error is reproducible and not in safe mode

Sorry just to confirm, do you mean the error can't be reproduce in safe mode?
