### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by makixi** [atom/github#1045]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:160

Error: kill EPERM
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.kill (internal/child_process.js:392:26)
    at Task.module.exports.Task.terminate (~/AppData/Local/atom/app-1.18.0/resources/app/src/task.js:154:31)
    at GitRepository.module.exports.GitRepository.refreshStatus (~/AppData/Local/atom/app-1.18.0/resources/app/src/git-repository.js:391:20)
    at GithubPackage.refreshAtomGitRepository (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/github-package.js:537:44)
    at GithubPackage.subscriptions._eventKit.CompositeDisposable.contextPool.onDidChangeWorkdirOrHead.context (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/github-package.js:165:18)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/models/workdir-context-pool.js:65:45)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at WorkdirContext.subs.add.observer.onDidChangeWorkdirOrHead (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/models/workdir-context.js:130:83)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at FileSystemChangeObserver.didChangeWorkdirOrHead (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/models/file-system-change-observer.js:71:24)
    at _this3.currentFileWatcher.debounceMS (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/models/file-system-change-observer.js:109:28)
```

### Commands

```
```

### Non-Core Packages

```
autoclose-html 0.23.0 
language-markdown 0.25.1 
markdown-preview-plus 2.4.10 
markdown-writer 2.6.5 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
