### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isChanged' of undefined

### ISSUE THREAD

**Issue by Tankernn** [atom/github#1059]
Steps to reproduce:

1. Edit some lines in a file in a repo.
2. Open diff view.
3. Select the additions and deletions.
4. Right-click the selection.
5. [error]
6. Right-click again.
7. Context menu shows up.
8. Click 'Stage Selection'
9. [2x the same error as before], see below

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'isChanged' of undefined

```
At /usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:32

TypeError: Cannot read property 'isChanged' of undefined
    at Object.isItemSelectable (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:32:109)
    at ListSelection.isItemSelectable (/usr/share/atom/resources/app/node_modules/github/lib/views/list-selection.js:80:31)
    at ListSelection.getSelectedItems (/usr/share/atom/resources/app/node_modules/github/lib/views/list-selection.js:278:24)
    at FilePatchSelection.getSelectedLines (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:331:40)
    at FilePatchView.contextMenuOnItem (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-view.js:273:63)
    at Object.contextMenuOnItem (/usr/share/atom/resources/app/node_modules/github/lib/views/hunk-view.js:115:65)
    at onWillShowContextMenu (/usr/share/atom/resources/app/node_modules/github/lib/views/hunk-view.js:178:58)
    at Function.handle (/usr/share/atom/resources/app/node_modules/github/lib/context-menu-interceptor.js:32:15)
    at HTMLDocument.contextMenuHandler (/usr/share/atom/resources/app/node_modules/github/lib/context-menu-interceptor.js:68:32)
```

### Commands

```
     -9:39 core:move-right (input.hidden-input)
     -9:38.5.0 intentions:highlight (input.hidden-input)
     -9:38.4.0 core:save (input.hidden-input)
     -9:35.2.0 intentions:highlight (input.hidden-input)
     -9:35.1.0 core:save (input.hidden-input)
     -9:16.7.0 core:backspace (input.hidden-input)
  2x -9:15.5.0 core:move-down (input.hidden-input)
     -9:14.3.0 intentions:highlight (input.hidden-input)
     -9:14.2.0 core:save (input.hidden-input)
  6x -9:12.6.0 core:move-right (input.hidden-input)
     -9:10 autocomplete-plus:confirm (input.hidden-input)
     -9:09.3.0 intentions:highlight (input.hidden-input)
     -9:09.3.0 core:save (input.hidden-input)
     -0:58 core:confirm (div.github-HunkView-lineContent)
     -0:48 github:discard-selected-lines (div.github-HunkView-lineNumber.is-new)
  9x -0:45.1.0 core:confirm (div.github-HunkView-lineNumber.is-new)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autoclose-html 0.23.0 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
intentions 1.1.2 
language-rust 0.4.11 
linter 2.2.0 
linter-python-pep8 0.2.0 
linter-rust 0.8.0 
linter-ui-default 1.6.3 
python-tools 0.6.9 
tabs-to-spaces 1.0.3 
```

**Comment by Tankernn** [comment]
Saw the other, identical issue now, sorry.
