### ISSUE TITLE
Uncaught Error: C:/xampp\htdocs\testsite\wordpress\wp-content\themes\testsite_theme\sidebar.php d...

### ISSUE THREAD

**Issue by melbell15** [atom/github#1064]
[Enter steps to reproduce:]
Hi! I'm new to web development and atom, but when I was working with my code and trying to preview it I got this error message and I have no clue how to get rid of it or what it means. If anyone knows how to solve this so that I can see the work that I've done so far please let me know. And if there are any resources that you may know of that will help me to become more familiar with atom and developing themes with wordpress please let me know as well. Thanks!
1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: C:\xampp\htdocs\testsite\wordpress\wp-content\themes\testsite_theme\sidebar.php does not belong to repo null

```
At C:\Users\Mel\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\xampp\htdocs\testsite\wordpress\wp-content\themes\testsite_theme\sidebar.php does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:13.5.0 core:undo (input.hidden-input)
     -7:11.3.0 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -4:50.2.0 spell-check:correct-misspelling (div.line)
     -4:02.5.0 markdown-preview:toggle (input.hidden-input)
     -3:41.9.0 open-on-github:issues (input.hidden-input)
  2x -1:39.2.0 window:increase-font-size (input.hidden-input)
  2x -1:31.2.0 window:decrease-font-size (input.hidden-input)
     -0:11.3.0 github:view-unstaged-changes-for-current-file (div.lines)
```

### Non-Core Packages

```

```

**Comment by ungb** [comment]
@melbell15, I'm currently trying to pinpoint this issue down and figure out what's causing it.  Can you provide any additional info about the Repository you're using? Are you using symlinks with this repository?  

I am not able to repro the issue, but it seems like a few users are running into the same issue. 
 There's issue https://github.com/atom/github/issues/950 that a lot of people have seen similar issue but seems like different cases. 

Are you able to consistently repro the issue?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/github/issues/1064#issuecomment-319799316. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
