### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isChanged' of undefined

### ISSUE THREAD

**Issue by marlongb** [atom/github#1079]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'isChanged' of undefined

```
At /usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:32

TypeError: Cannot read property 'isChanged' of undefined
    at Object.isItemSelectable (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:32:109)
    at ListSelection.isItemSelectable (/usr/share/atom/resources/app/node_modules/github/lib/views/list-selection.js:80:31)
    at ListSelection.getSelectedItems (/usr/share/atom/resources/app/node_modules/github/lib/views/list-selection.js:278:24)
    at FilePatchSelection.getSelectedLines (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:331:40)
    at FilePatchSelection.getSelectedHunks (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:259:40)
    at FilePatchView.render (/usr/share/atom/resources/app/node_modules/github/lib/views/file-patch-view.js:112:54)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:799:36)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:822:38)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:746:42)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:561:18)
    at Object.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:157:28)
    at runBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:150:27)
    at ReactReconcileTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:89:38)
    at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:172:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:206:31)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:153:22)
    at Object.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
  2x -0:17.7.0 github:discard-selected-lines (div.github-HunkView-lineNumber.is-new)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.3 
symbol-gen 1.3.1 
```

**Comment by 50Wliu** [comment]
Fixed by #1072.
