### ISSUE TITLE
Uncaught Error: $ATOM_HOME/mauroPython/prueba.py does not belong to repo null

### ISSUE THREAD

**Issue by mauro37ar** [atom/github#1083]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: /home/mauro/.atom/mauroPython/prueba.py does not belong to repo null

```
At /usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:807

Error: /home/mauro/.atom/mauroPython/prueba.py does not belong to repo null
    at RootController.viewChangesForCurrentFile (/usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (/usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:56.8.0 autocomplete-plus:confirm (input.hidden-input)
     -1:56.1.0 editor:newline (input.hidden-input)
  2x -1:53.8.0 core:move-left (input.hidden-input)
     -1:39.8.0 autocomplete-plus:activate (atom-text-editor#core.ignoredNames.editor.mini)
     -1:38.6.0 core:move-left (input.hidden-input)
  3x -1:29.9.0 core:delete (input.hidden-input)
     -1:28.5.0 core:backspace (input.hidden-input)
     -1:27.7.0 core:delete (input.hidden-input)
     -1:14.6.0 core:backspace (input.hidden-input)
  2x -1:05.1.0 core:move-up (input.hidden-input)
     -1:03.3.0 editor:newline (input.hidden-input)
  5x -0:53.8.0 core:move-left (input.hidden-input)
 13x -0:51.7.0 core:move-right (input.hidden-input)
  6x -0:50.2.0 core:move-down (input.hidden-input)
     -0:46.7.0 core:save (input.hidden-input)
     -0:17.1.0 github:view-staged-changes-for-current-file (div.lines)
```

### Non-Core Packages

```
autocomplete-python 1.9.1 
```

**Comment by BinaryMuse** [comment]
Fixed by https://github.com/atom/github/pull/1076, yet to be released.
