### ISSUE TITLE
Uncaught Error: ~/Documents\Machine Learning\LinearRegression.py does not belong to repo null

### ISSUE THREAD

**Issue by dharmang007** [atom/github#1086]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: C:\Users\Dharmang\Documents\Machine Learning\LinearRegression.py does not belong to repo null

```
At C:\Users\Dharmang\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\Dharmang\Documents\Machine Learning\LinearRegression.py does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -7:35.2.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:22.1.0 git-control:toggle (atom-pane.pane.active)
  2x -6:45.4.0 core:paste (input.hidden-input)
     -1:50.5.0 symbols-view:toggle-file-symbols (div.github-Panel.is-empty)
     -0:53.3.0 command-palette:toggle (div.github-Panel.is-empty)
     -0:48.4.0 core:move-down (input.hidden-input)
     -0:48 core:move-up (input.hidden-input)
  6x -0:47 core:move-down (input.hidden-input)
  6x -0:41.7.0 core:move-up (input.hidden-input)
     -0:39.7.0 core:confirm (input.hidden-input)
     -0:39.7.0 github:view-unstaged-changes-for-current-file (div.github-Panel.is-empty)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
atom-runner 2.7.1 
autocomplete-python 1.9.1 
git-control 0.9.0 
platformio-ide-terminal 2.5.3 
script 3.15.0 
```

**Comment by BinaryMuse** [comment]
Dup of https://github.com/atom/github/issues/982
