### ISSUE TITLE
Line-ending selector is sometimes visible on diff views

### ISSUE THREAD

**Issue by 50Wliu** [atom/github#1094]
Sometimes (I believe after a commit?) the line-ending tile (LF/CRLF) in the status bar will be visible.  Clicking it generates an exception; however notifications ends up throwing an exception while trying to process the exception so I'm unsure what the actual exception is (exceptionception!).

Atom 1.20.0-dev-cb08c1b87, Windows 10 x64.

**Comment by rsese** [comment]
Stack trace from https://github.com/atom/atom/issues/15639 where a few other folks ran into this:

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:81:44)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:33:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:353:24)
    at CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:266:23)
    at HTMLAnchorElement.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/line-ending-selector/lib/main.js:181:25)
```

**Comment by upeksha1996** [comment]
[Enter steps to reproduce:]

Not sure.. It always appeared when im trying to add files to the git.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /opt/atom/resources/app/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/opt/atom/resources/app/node_modules/notifications/lib/command-logger.js:81:44)
    at /opt/atom/resources/app/node_modules/notifications/lib/command-logger.js:33:30
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:353:24)
    at CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:266:23)
    at HTMLAnchorElement.<anonymous> (/opt/atom/resources/app/node_modules/line-ending-selector/lib/main.js:161:25)
```

### Commands

```
```

### Non-Core Packages

```
language-blade 0.38.0 
laravel 0.7.1 
laravel-forms-bootstrap-snippets 1.2.0 
```

**Comment by maxim-lian** [comment]
I'm a newbie at customizing Atom, so not sure how helpful this is, but I get this when I:

- Have the diff view focused in a pane
- Click into the commit box
- Run the below function (which is in my init script). I built it from some copy & pasting, so it may be the function's fault:

```

atom.commands.add 'atom-workspace',
  'custom:commit-and-push': ->
    editor = atom.workspace.getActivePane()
    editor.saveActiveItem()
    editorElement = atom.views.getView(atom.workspace.getActiveTextEditor())
    atom.commands.dispatch(editorElement, 'github:commit')
    atom.commands.dispatch(editorElement, 'github:push')
```

Running either `git:commit` or `git:push` does not trigger the error. Not does it trigger if the last pane selected was code.

**Comment by Shadowtail117** [comment]
Sorry for the bump, but I just installed Atom and can confirm the bug as well. All I had to do was click on the line endings icon (which was "CRLF" at the time) in the status bar.
```
**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

```
At C:\Users\\[Me]\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'webkitMatchesSelector' of undefined
    at CommandRegistry.handleCommandEvent (\~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:349795)
    at CommandRegistry.dispatch (\~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:348492)
    at HTMLAnchorElement.<anonymous> (\~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:202627)
```

### Commands

```
     -5:51.4.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:33.6.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:32.6.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:30.8.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:58.9.0 core:confirm (input.hidden-input)
     -2:54.6.0 core:move-left (input.hidden-input)
     2x -2:53.6.0 core:backspace (input.hidden-input)
     -2:45.3.0 core:select-all (input.hidden-input)
     2x -2:45 core:paste (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.13.3 
```
