### ISSUE TITLE
Uncaught Error: *path_to_file* does not belong to repo null

### ISSUE THREAD

**Issue by exfool** [atom/github#1116]
Hi,

I have no idea, this is a correct error or an unexpected. To improve the Atom describe her playing.

[Steps to reproduce:]

1. Open single file without any version controll.
2. Right click to code area
3. Click to View Unstaged Changes

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: /Users/exfool/Desktop/code/2.html does not belong to repo null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807

Error: /Users/exfool/Desktop/code/2.html does not belong to repo null
    at RootController.viewChangesForCurrentFile (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -7:07.1.0 core:save (input.hidden-input)
  2x -3:59.6.0 core:backspace (input.hidden-input)
     -3:56.9.0 bracket-matcher:remove-matching-brackets (input.hidden-input)
     -3:52.6.0 window:decrease-font-size (input.hidden-input)
  3x -3:51.7.0 window:increase-font-size (input.hidden-input)
     -3:48.5.0 window:decrease-font-size (input.hidden-input)
     -3:45.2.0 core:move-left (input.hidden-input)
     -3:44.3.0 editor:newline (input.hidden-input)
     -3:42.6.0 core:select-right (input.hidden-input)
     -3:41.8.0 core:cut (input.hidden-input)
  2x -3:40.4.0 core:undo (input.hidden-input)
     -3:30.8.0 core:select-left (input.hidden-input)
     -3:30.1.0 core:cut (input.hidden-input)
     -3:28.7.0 core:paste (input.hidden-input)
  3x -3:27.2.0 core:undo (input.hidden-input)
     -0:36.2.0 github:view-unstaged-changes-for-current-file (div.line-number.foldable)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-clock 0.1.13 
language-docker 1.1.8 
language-gitignore 0.3.0 
language-latex 1.1.0 
language-lua 0.9.11 
language-matlab 0.2.1 
latex 0.45.0 
latexer 0.3.0 
latextools 0.8.5 
pdf-view 0.59.0 
preview-inline 1.4.7 
```

**Comment by 50Wliu** [comment]
Thanks for the report @exfool!  This has already been fixed in the Atom 1.20 betas.
