### ISSUE TITLE
Uncaught Error: ~/Desktop\Appshow\index.html.txt does not belong to repo null

### ISSUE THREAD

**Issue by wood12** [atom/github#1124]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: C:\Users\PC\Desktop\Appshow\index.html.txt does not belong to repo null

```
At C:\Users\PC\AppData\Local\atom\app-1.19.2\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\PC\Desktop\Appshow\index.html.txt does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.2/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.2/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.2/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.2/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.2/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:35.8.0 github:view-staged-changes-for-current-file (span.syntax--meta.syntax--paragraph.syntax--text)
```

### Non-Core Packages

```
apex-syntax 0.1.0 
bootstrap-3-snippets-for-atom 1.5.0 
django-templates 0.5.0 
emmet-snippets-compatibility 1.0.6 
genesis-snippets 2.1.0 
html-shorcuts-react 1.1.1 
language-octobercms 2.1.1 
```

**Comment by 50Wliu** [comment]
Fixed in Atom 1.20.0, currently in beta.
