### ISSUE TITLE
Uncaught Error: ~/Desktop/gitsrc/aptsrc/transmission-2.84/libtransmission/utils.c does not belong...

### ISSUE THREAD

**Issue by vicksun001** [atom/github#1135]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: /Users/vick.sun/Desktop/gitsrc/aptsrc/transmission-2.84/libtransmission/utils.c does not belong to repo null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807

Error: /Users/vick.sun/Desktop/gitsrc/aptsrc/transmission-2.84/libtransmission/utils.c does not belong to repo null
    at RootController.viewChangesForCurrentFile (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:21.9.0 symbols-view:toggle-file-symbols (input.hidden-input)
 19x -5:20.8.0 core:move-down (input.hidden-input)
     -5:18.1.0 core:move-up (input.hidden-input)
     -5:17.7.0 core:confirm (input.hidden-input)
  2x -5:13.9.0 atom-gtags:get-symbols-of-file (input.hidden-input)
     -5:08.9.0 core:confirm (input.hidden-input)
     -4:59.7.0 atom-gtags:get-definitions (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -4:57.8.0 atom-gtags:get-references (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:54.1.0 atom-gtags:get-symbols-of-file (input.hidden-input)
     -4:52.7.0 core:confirm (input.hidden-input)
  2x -4:48.3.0 core:close (input.hidden-input)
     -4:36.7.0 core:confirm (input.hidden-input)
     -3:35.1.0 core:paste (input.hidden-input)
     -1:54.7.0 atom-ctags:rebuild (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -1:39.4.0 symbols-view:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -0:21.8.0 github:view-unstaged-changes-for-current-file (span.syntax--entity.syntax--name.syntax--function.syntax--c)
```

### Non-Core Packages

```
atom-ctags 5.1.0 
atom-gtags 0.5.7 
autocomplete-ctags 0.4.1 
gpp-compiler 3.0.7 
```

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.20.0.
