### ISSUE TITLE
C:\Users\Tomek\github

### ISSUE THREAD

**Issue by frontz** [atom/github#1140]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: E:\CSS\l1.html does not belong to repo null

```
At C:\Users\Tomek\AppData\Local\atom\app-1.19.3\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: E:\CSS\l1.html does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.3/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.3/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:00.9.0 dev-live-reload:reload-all (ul.list-inline.tab-bar.inset-panel)
     -2:51.4.0 github:toggle-git-tab (input.hidden-input)
     -2:19 github:view-staged-changes-for-current-file (div.line.cursor-line)
     -1:24.1.0 github:toggle-git-tab (input.hidden-input)
     -1:16.3.0 core:paste (span.syntax--text.syntax--plain.syntax--null-grammar)
     -0:41.8.0 github:toggle-git-tab (ul.list-inline.tab-bar.inset-panel)
     -0:24.7.0 core:copy (input.hidden-input)
     -0:07.7.0 github:view-staged-changes-for-current-file (div.line)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.20.0.
