### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1142]
**Steps to reproduce:**

![emitter has been disposed 3](https://user-images.githubusercontent.com/1058982/29864669-b6eca34c-8d73-11e7-8982-49f8c47b9063.gif)

**Atom**: 1.19.4 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At C:\Users\lineri\AppData\Local\atom\app-1.19.4\resources\app\node_modules\event-kit\lib\emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/event-kit/lib/emitter.js:77:21)
    at StubItem.onDidDestroy (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/github/lib/atom-items/stub-item.js:136:31)
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.19.4/resources/app/src/pane.js:521:42)
    at Pane.module.exports.Pane.moveItemToPane (~/AppData/Local/atom/app-1.19.4/resources/app/src/pane.js:676:25)
    at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/tabs/lib/tab-bar-view.js:766:26)
    at TabBarView.module.exports.TabBarView.onDrop (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/tabs/lib/tab-bar-view.js:645:29)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by Ben3eeE** [comment]
Can still reproduce this issue with:

Atom : 1.28.0-dev-603dc5a05
Electron: 1.7.11
Chrome : 58.0.3029.110
Node : 7.9.0
Github 0.14.0

**Comment by gchhablani** [comment]
I am facing a similar error as well when I try to enable the GitHub package.

**Comment by theresa-lim** [comment]
I am also running into this error when enabling the GitHub package
