### ISSUE TITLE
Uncaught Error: ~/Documents/Coding folder/wow.html does not belong to repo null

### ISSUE THREAD

**Issue by Adrian-Samuel** [atom/github#1143]
[Enter steps to reproduce:]

1. ... Open atom via terminal in safe mode
2. ... Open a file and then right click to view staged changes...and this error appears

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: /Users/adrian/Documents/Coding folder/wow.html does not belong to repo null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807

Error: /Users/adrian/Documents/Coding folder/wow.html does not belong to repo null
    at RootController.viewChangesForCurrentFile (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  6x -1:25.9.0 core:backspace (input.hidden-input)
     -1:17.4.0 application:open (input.hidden-input)
  2x -0:42.4.0 editor:newline (input.hidden-input)
  8x -0:39.1.0 core:backspace (input.hidden-input)
  2x -0:36 editor:newline (input.hidden-input)
     -0:35.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:35.2.0 snippets:expand (atom-text-editor.editor.is-focused)
  2x -0:31.9.0 core:backspace (input.hidden-input)
     -0:23 core:save (input.hidden-input)
     -0:15.4.0 github:view-staged-changes-for-current-file (div.line)
```

### Non-Core Packages

```

```

**Comment by BinaryMuse** [comment]
This is fixed in the upcoming 1.20 release.
