### ISSUE TITLE
Uncaught Error: D:/WEB\js\slider\index.html does not belong to repo null

### ISSUE THREAD

**Issue by Quadrad1** [atom/github#1144]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: D:\WEB\js\slider\index.html does not belong to repo null

```
At C:\Users\Ситдиков\AppData\Local\atom\app-1.19.5\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: D:\WEB\js\slider\index.html does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.5/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.5/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:59.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:27.8.0 core:undo (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--hex.syntax--css)
     -0:25.5.0 core:redo (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--hex.syntax--css)
     -0:20.5.0 encoding-selector:show (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--hex.syntax--css)
     -0:15.5.0 github:view-unstaged-changes-for-current-file (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--hex.syntax--css)
     -0:02.7.0 color-picker:open (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--hex.syntax--css)
```

### Non-Core Packages

```
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.4 
highlight-selected 0.13.1 
language-jade 0.7.2 
minimap 4.28.2 
pdf-view 0.59.0 
texter 0.1.0 
```

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.20, currently in beta.
