### ISSUE TITLE
Uncaught Error: ~/Pictures\login.htm does not belong to repo null

### ISSUE THREAD

**Issue by vmckenna87** [atom/github#1146]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: C:\Users\nessa\Pictures\login.htm does not belong to repo null

```
At C:\Users\nessa\AppData\Local\atom\app-1.19.5\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\nessa\Pictures\login.htm does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.5/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.5/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -4:55.1.0 application:open-file (ul.list-inline.tab-bar.inset-panel)
     -1:58.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:50.3.0 encoding-selector:show (atom-text-editor.editor)
  3x -1:23.1.0 tree-view:reveal-active-file (div.line)
     -0:24.4.0 github:view-staged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
Hydrogen 1.20.0 
```

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.20, currently in beta.
