### ISSUE TITLE
Uncaught Error: C:/Windows\WinSxS\amd64_microsoft-windows-autoconv.resources_31bf3856ad364e35_10....

### ISSUE THREAD

**Issue by vmckenna87** [atom/github#1147]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: C:\Windows\WinSxS\amd64_microsoft-windows-autoconv.resources_31bf3856ad364e35_10.0.14393.1532_en-us_7c5e39ccf5b4d9be\autoconv.exe.mui does not belong to repo null

```
At C:\Users\nessa\AppData\Local\atom\app-1.19.5\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Windows\WinSxS\amd64_microsoft-windows-autoconv.resources_31bf3856ad364e35_10.0.14393.1532_en-us_7c5e39ccf5b4d9be\autoconv.exe.mui does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.5/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.5/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.5/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:58.5.0 application:open-file (ul.list-inline.tab-bar.inset-panel)
  2x -1:42.3.0 encoding-selector:show (span.syntax--meta.syntax--arguments.syntax--js)
     -0:57.8.0 tree-view:reveal-active-file (span.syntax--meta.syntax--arguments.syntax--js)
     -0:31.9.0 pane:close (span.syntax--meta.syntax--arguments.syntax--js)
     -0:16.8.0 encoding-selector:show (div.line)
     -0:16.7.0 github:view-unstaged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
Hydrogen 1.20.0 
```

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.20, currently in beta.
