### ISSUE TITLE
Uncaught Error: ~/AppData\Local\Steam\htmlcache\Visited Links does not belong to repo null

### ISSUE THREAD

**Issue by knippe** [atom/github#1154]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Microsoft 
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: C:\Users\pitr\AppData\Local\Steam\htmlcache\Visited Links does not belong to repo null

```
At C:\Users\pitr\AppData\Local\atom\app-1.19.6\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\pitr\AppData\Local\Steam\htmlcache\Visited Links does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.6/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.6/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.6/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.6/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.6/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -0:41.5.0 spell-check:correct-misspelling (div.line)
     -0:22.1.0 symbols-view:go-to-declaration (span.syntax--text.syntax--plain.syntax--null-grammar)
     -0:13.2.0 encoding-selector:show (div.line)
     -0:06.4.0 github:view-unstaged-changes-for-current-file (span.syntax--text.syntax--plain.syntax--null-grammar)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.0.1 
atom-clock 0.1.15 
dash-ui 0.4.2 
hey-pane 1.0.0 
Hydrogen 1.21.1 
chester-atom-syntax 0.3.0 
chestnut-light-atom-syntax 0.2.1 
my-package 0.0.0 
my-theme-syntax 0.0.0 
piatto-light-syntax 0.2.2 
pristine-ui 1.1.7 
pure-syntax 0.3.0 
scroll-through-time 0.2.0 
toggler 0.3.0 
zentabs 0.8.8 
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.20.0, currently in beta.
