### ISSUE TITLE
Uncaught Error: C:/Users\DREAME~1\AppData\Local\Temp\ehlibusiness.com\public_html\admin\inc\actio...

### ISSUE THREAD

**Issue by zeydo** [atom/github#1156]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: C:\Users\DREAME~1\AppData\Local\Temp\ehlibusiness.com\public_html\admin\inc\actions.php does not belong to repo null

```
At C:\Users\Dreamer-Zeyd\AppData\Local\atom\app-1.19.6\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\DREAME~1\AppData\Local\Temp\ehlibusiness.com\public_html\admin\inc\actions.php does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.6/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.6/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.6/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.6/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.6/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:16.3.0 core:save (input.hidden-input)
     -2:30.9.0 core:backspace (input.hidden-input)
     -2:24.1.0 command-palette:toggle (input.hidden-input)
  3x -2:21.2.0 core:backspace (input.hidden-input)
     -2:10 core:move-up (input.hidden-input)
     -2:09.4.0 core:move-down (input.hidden-input)
     -2:08.9.0 core:move-up (input.hidden-input)
     -2:08.4.0 core:backspace (input.hidden-input)
 24x -1:15.4.0 core:move-down (input.hidden-input)
     -1:06.3.0 editor:consolidate-selections (input.hidden-input)
     -1:06.3.0 core:cancel (input.hidden-input)
     -0:52.9.0 settings-view:open (input.hidden-input)
     -0:48.7.0 core:confirm (input.hidden-input)
     -0:21.4.0 auto-indent:apply (div.line)
     -0:13.6.0 github:view-unstaged-changes-for-current-file (div.line)
     -0:00.0 github:view-staged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-php 1.1.1 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-clock 0.1.15 
atom-meld 0.3.5 
atom-mysql-snippets 0.3.1 
auto-indent 0.5.0 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
bootstrap-3-snippetset 0.0.6 
bootstrap3-snippets 0.1.2 
clipboard-history 0.6.6 
emmet 2.4.3 
fold-functions 0.5.0 
ftp-remote-edit 0.11.11 
language-blade 0.34.0 
local-history 4.3.0 
obsidian-syntax 0.2.0 
php-cs-fixer 4.1.1 
platformio-ide-terminal 2.6.0 
Remote-FTP 1.1.3 
```

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.20.0, currently in beta.
