### ISSUE TITLE
Uncaught Error: ~/AppData\Local\Temp\Temp1_com.farproc.wifi.analyzer_132.zip\com.farproc.wifi.ana...

### ISSUE THREAD

**Issue by vmckenna87** [atom/github#1166]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: C:\Users\nessa\AppData\Local\Temp\Temp1_com.farproc.wifi.analyzer_132.zip\com.farproc.wifi.analyzer_132.apk does not belong to repo null

```
At C:\Users\nessa\AppData\Local\atom\app-1.19.7\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\nessa\AppData\Local\Temp\Temp1_com.farproc.wifi.analyzer_132.zip\com.farproc.wifi.analyzer_132.apk does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.7/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.7/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:47 hydrogen:run-and-move-down (input.hidden-input)
     -1:35.5.0 editor:fold-at-indent-level-1 (input.hidden-input)
     -1:15.5.0 core:backspace (input.hidden-input)
     -0:41.9.0 pane:split-left-and-copy-active-item (span.syntax--text.syntax--plain.syntax--null-grammar)
     -0:11 github:view-unstaged-changes-for-current-file (div.line-number.cursor-line)
```

### Non-Core Packages

```
hey-pane 1.0.0 
Hydrogen 1.21.1 
```

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.20.0, currently in beta.
