### ISSUE TITLE
Uncaught Error: C:/xampp\htdocs\UsedCarsystem\config.ini\config.ini.php does not belong to repo null

### ISSUE THREAD

**Issue by Aphisit25** [atom/github#1168]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [github](https://github.com/atom/github) package 0.3.4-1

### Stack Trace

Uncaught Error: C:\xampp\htdocs\UsedCarsystem\config.ini\config.ini.php does not belong to repo null

```
At C:\Users\APHISIT\AppData\Local\atom\app-1.19.7\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\xampp\htdocs\UsedCarsystem\config.ini\config.ini.php does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.7/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.7/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -7:02.8.0 editor:select-to-first-character-of-line (input.hidden-input)
     -6:58.1.0 window:toggle-menu-bar (input.hidden-input)
     -2:55.2.0 core:move-down (input.hidden-input)
     -2:55.1.0 autocomplete-plus:confirm (input.hidden-input)
     -2:55.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:47.9.0 core:move-right (input.hidden-input)
     -2:44 editor:select-to-first-character-of-line (input.hidden-input)
  2x -2:43.2.0 core:backspace (input.hidden-input)
     -2:41 core:save (input.hidden-input)
  2x -1:22.2.0 encoding-selector:show (div.line)
     -0:55.4.0 tree-view:reveal-active-file (div.lines)
     -0:52.8.0 symbols-view:go-to-declaration (div.lines)
     -0:50.2.0 spell-check:correct-misspelling (div.lines)
     -0:48.2.0 github:view-staged-changes-for-current-file (div.lines)
     -0:14.2.0 spell-check:correct-misspelling (div.lines)
     -0:11.4.0 github:view-unstaged-changes-for-current-file (div.lines)
```

### Non-Core Packages

```
atom-clock 0.1.15 
chester-atom-syntax 0.3.0 
piatto-light-syntax 0.2.2 
toggler 0.3.0 
```

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.20.0, released today.
