### ISSUE TITLE
Github package error "Uncaught (in promise) TypeError: validateDOMNesting.updatedAncestorInfo is not a function"

### ISSUE THREAD

**Issue by megaultrachicken** [atom/github#1173]
Github and Git tabs do not open. Even with only core packages installed or reinstalling altogether.
### Steps to Reproduce

1. Can't open the Git tab at anytime.

### Versions

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
OS: Windows 7 x64
Node    : 7.4.0

### Stack Trace
Uncaught (in promise) TypeError: validateDOMNesting.updatedAncestorInfo is not a function
    at ReactDOMContainerInfo (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactDOMContainerInfo.js:27:58)
    at mountComponentIntoNode (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactMount.js:104:89)
    at ReactReconcileTransaction.perform (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\Transaction.js:143:26)
    at batchedMountComponentIntoNode (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactMount.js:126:21)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\Transaction.js:143:26)
    at Object.batchedUpdates (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactUpdates.js:97:33)
    at Object._renderNewRootComponent (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactMount.js:319:24)
    at Object._renderSubtreeIntoContainer (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactMount.js:401:38)
    at Object.render (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\react-dom\lib\ReactMount.js:422:29)
    at GithubPackage.rerender (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\github\lib\github-package.js:335:30)
    at C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\github\lib\github-package.js:304:19
    at Generator.next (<anonymous>)
    at step (C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\github\lib\github-package.js:96:197)
    at C:\Users\043831\AppData\Local\atom\app-1.20.0\resources\app\node_modules\github\lib\github-package.js:96:367

**Comment by jacortinas** [comment]
I'm seeing this same issue, the error only shows up in the developer console the first time the tabs are attempted to be opened. This is even after a completely fresh installation of 1.20 with only the core packages installed.

**Comment by BinaryMuse** [comment]
@megaultrachicken Do you by chance have the `NODE_ENV` environment variable set? If so, what to?

**Comment by megaultrachicken** [comment]
@BinaryMuse I did actually and it was to 'development', I just removed it since it was left over from a previous project, restarted my laptop, reinstalled Atom and it works now. Thank you!

**Comment by BinaryMuse** [comment]
Okay, great — well, sort of, this is a dup of https://github.com/atom/github/issues/833. Thanks for the update!
