### ISSUE TITLE
Git panel show noting after modified files, and there's a error in console

### ISSUE THREAD

**Issue by yubaoquan** [atom/github#1189]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Git panel didn't show the staged or unstaged changes.

### Steps to Reproduce

1. Rename a file in repo, (app.js => app.js.bak)
2. Make a soft link of the same filename in step1 from another place `ln -s /some/other/place/app.js ./app.js`
3. Toggle the Github/Git panel.

**Expected behavior:** 

Show the changes. 

**Actual behavior:**

Show nothing and produces an error in console.

**Reproduces how often:**
100%

### Versions

Atom    : 1.21.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.11.0

Sierra 10.12.6 

#### screen snapshot

<img width="938" alt="screen shot 2017-09-24 at 7 28 01 pm" src="https://user-images.githubusercontent.com/2340296/30782156-295c1354-a0f2-11e7-85e1-3dfe90a79b9d.png">

#### error trace
Uncaught (in promise) TypeError: Cannot read property '8' of null
    at parseChangedEntry (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/what-the-status/index.js:128:26)
    at parseLine (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/what-the-status/index.js:69:13)
    at Stream.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/what-the-status/index.js:41:37)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/through/index.js:40:22)
    at Stream.stream.queue.stream.push (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/through/index.js:49:11)
    at emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/split/index.js:41:20)
    at next (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/split/index.js:53:13)
    at Stream.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/split/index.js:58:11)
    at Stream.stream.write (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/through/index.js:30:17)
    at Readable.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at emitReadable_ (_stream_readable.js:433:3)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by hex007** [comment]
Modified files don't show up in Git Tab on save.

**Comment by ginkgomzd** [comment]
I'm having the same problem, although I think it pertains to all changes, not just the steps to reproduce.
My steps to reproduce:
* Open the GitHub Tab
* make any kind of change to a file that was not changed before opening the Tab.
* Observe that new modified file is not listed in Tab.
* Toggle view of Tab has no effect.

Only way to trigger an update of the modification list is to change windows in the desktop. When returning to Atom, the Tab is updated.

**Comment by rsese** [comment]
Thanks for the report @yubaoquan - I can reproduce on macOS 10.12.6 with Atom 1.23.1 with your steps,  /cc @kuychaco @BinaryMuse :v:

@ginkgomzd - I don't see the the behavior you described, can you open a new issue for that and fill out the issue template so we can take a look?

**Comment by BinaryMuse** [comment]
Thanks for the issue. This is a manifestation of https://github.com/atom/github/issues/310, so I'm going to close this in favor of that issue. Feel free to follow along there for updates.

Dup of https://github.com/atom/github/issues/310
