### ISSUE TITLE
Uncaught TypeError: Cannot read property 'promptForCredentials' of null

### ISSUE THREAD

**Issue by dallinmoak** [atom/github#1192]
all I did was compile a cpp file and then modify it a bit and then saved and *i thought* pushed the changes to github. (i'm new to this so it was probably my fault)

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [github](https://github.com/atom/github) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'promptForCredentials' of null

```
At /private/var/folders/_0/1w5347xd1vb3hn5l1m_q85f40000gn/T/AppTranslocation/F87EAFDD-EC9C-4EA6-AAAF-5774421FA474/d/Atom.app/Contents/Resources/app/node_modules/github/lib/github-package.js:159

TypeError: Cannot read property 'promptForCredentials' of null
    at GitPromptServer.promptCallback (/private/var/folders/_0/1w5347xd1vb3hn5l1m_q85f40000gn/T/AppTranslocation/F87EAFDD-EC9C-4EA6-AAAF-5774421FA474/d/Atom.app/Contents/Resources/app/node_modules/github/lib/github-package.js:159:53)
    at GitPromptServer.handleData (/private/var/folders/_0/1w5347xd1vb3hn5l1m_q85f40000gn/T/AppTranslocation/F87EAFDD-EC9C-4EA6-AAAF-5774421FA474/d/Atom.app/Contents/Resources/app/node_modules/github/lib/git-prompt-server.js:134:32)
    at Socket.connection.on.data (/private/var/folders/_0/1w5347xd1vb3hn5l1m_q85f40000gn/T/AppTranslocation/F87EAFDD-EC9C-4EA6-AAAF-5774421FA474/d/Atom.app/Contents/Resources/app/node_modules/github/lib/git-prompt-server.js:117:24)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -1:50.7.0 core:move-down (input.hidden-input)
  4x -1:50.3.0 core:backspace (input.hidden-input)
  2x -0:59.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you reproduce the error or did you hit it just once?  And are you having any trouble pushing now?

**Comment by dallinmoak** [comment]
It was just a one-time thing. I ended up re-installing the whole thing a couple days ago for other reasons. Can't reproduce. pushing works now. Again, it was probably a user error.
