### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispatchEvent' of null

### ISSUE THREAD

**Issue by jaller94** [atom/github#1229]
[Enter steps to reproduce:]

1. Right click on a change and discard
2. If Atom is slow enough, you can right click and discard the change again (e.g. on big projects, slow computer or lots background processes)
3. The error will appear once you managed to discard a change twice.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'dispatchEvent' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:611

TypeError: Cannot read property 'dispatchEvent' of null
    at /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:611:40
```

### Commands

```
     -3:31.5.0 core:copy (input.hidden-input)
  5x -0:34 core:confirm (span.github-FilePatchListView-path)
  4x -0:11.5.0 github:discard-changes-in-selected-files (span.github-FilePatchListView-path)
```

### Non-Core Packages

```
busy-signal 1.4.3 
coffee-compile 0.27.0 
intentions 1.1.5 
language-babel 2.76.1 
language-lua 0.9.11 
linter 2.2.0 
linter-eslint 8.4.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
minimap-plus 4.29.2 
multi-wrap-guide 1.0.0 
```

**Comment by jaller94** [comment]
Here is the current version of Atom and the addon:
[Enter steps to reproduce:]

same as above

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'dispatchEvent' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:613

TypeError: Cannot read property 'dispatchEvent' of null
    at /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:613:40
```

### Commands

```
     -6:02.0 project-find:show (input.hidden-input)
     -5:57.6.0 core:confirm (input.hidden-input)
  6x -0:13.8.0 github:discard-changes-in-selected-files (span.github-FilePatchListView-path)
```

### Non-Core Packages

```
busy-signal 1.4.3 
coffee-compile 0.28.1 
file-icons 2.1.14 
intentions 1.1.5 
language-babel 2.79.0 
language-lua 0.9.11 
linter 2.2.0 
linter-eslint 8.4.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
minimap-plus 4.29.2 
multi-wrap-guide 1.0.0 
pigments 0.40.2 
```
