### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'getLines' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [atom/github#1241]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

![github stage nothing](https://user-images.githubusercontent.com/1058982/39043757-894c6580-448e-11e8-9dbf-173731260d10.gif)

### Steps to Reproduce

1. Open Atom in safe mode `.\atom --safe` from `cmd.exe`
2. Make changes to `foo.txt` and open the unstaged changes tab
3. Clear the selection
4. Right click outside the changes and pick `unstage selection`

**Expected behavior:**

Noop

**Actual behavior:**

```
Uncaught (in promise) TypeError: Cannot read property 'getLines' of undefined
    at FilePatch.getStagePatchForHunk (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\models\file-patch.js:48:65)
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\controllers\file-patch-controller.js:319:103
    at Generator.next (<anonymous>)
    at step (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\controllers\file-patch-controller.js:60:197)
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\controllers\file-patch-controller.js:60:443
    at C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\controllers\file-patch-controller.js:60:105
    at FilePatchController.stageHunk (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\controllers\file-patch-controller.js:321:13)
    at FilePatchController.stageOrUnstageHunk (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\controllers\file-patch-controller.js:339:25)
    at FilePatchController.attemptHunkStageOperation (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\controllers\file-patch-controller.js:357:16)
    at FilePatchView.setState (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\views\file-patch-view.js:524:26)
    at CallbackQueue.notifyAll (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\CallbackQueue.js:74:28)
    at ReactUpdatesFlushTransaction.close (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\ReactUpdates.js:57:30)
    at ReactUpdatesFlushTransaction.closeAll (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\Transaction.js:207:31)
    at ReactUpdatesFlushTransaction.perform (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\Transaction.js:154:22)
    at ReactUpdatesFlushTransaction.perform (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\ReactUpdates.js:87:38)
    at Object.flushBatchedUpdates (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\ReactUpdates.js:170:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\Transaction.js:207:31)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\Transaction.js:154:22)
    at Object.batchedUpdates (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:60:32)
    at Object.enqueueUpdate (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\ReactUpdates.js:198:28)
    at enqueueUpdate (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\ReactUpdateQueue.js:22:22)
    at Object.enqueueCallback (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react-dom\lib\ReactUpdateQueue.js:120:11)
    at FilePatchView.ReactComponent.setState (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\react\lib\ReactBaseClasses.js:64:24)
    at FilePatchView.didClickStageButtonForHunk (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\views\file-patch-view.js:523:18)
    at FilePatchView.didConfirm (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\node_modules\github\lib\views\file-patch-view.js:540:23)
    at CommandRegistry.handleCommandEvent (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\src\command-registry.js:381:36)
    at CommandRegistry.dispatch (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\src\command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\src\atom-environment.js:1388:34)
    at EventEmitter.outerCallback (C:\Users\abneyl\AppData\Local\atom\app-1.22.0-beta2\resources\app\src\application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.22.0-beta2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.2.windows.3
visual studio 2015
```

```
Atom : 1.28.0-dev-603dc5a05
Electron: 1.7.11
Chrome : 58.0.3029.110
Node : 7.9.0
```

### Additional Information

The files were located on a network share, staging actions can take a second or more.

**Comment by Ben3eeE** [comment]
Edited the issue to add steps to reproduce
