### ISSUE TITLE
Failed to initialize the github package

### ISSUE THREAD

**Issue by ghost** [atom/github#1259]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: linux 4.13.12-1-ARCH
**Thrown From**: [github](https://github.com/atom/github) package 0.7.0

### Stack Trace

Failed to initialize the github package

```
At Cannot call function 'isVisible' on missing remote object 1
Error: Cannot call function 'isVisible' on missing remote object 1
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

Error: Cannot call function 'isVisible' on missing remote object 1
Error: Cannot call function 'isVisible' on missing remote object 1
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:118:18)
    at new EventLogger (/usr/lib/atom/node_modules/github/lib/models/event-logger.js:25:55)
    at new WorkspaceChangeObserver (/usr/lib/atom/node_modules/github/lib/models/workspace-change-observer.js:71:19)
    at new WorkdirContext (/usr/lib/atom/node_modules/github/lib/models/workdir-context.js:102:57)
    at Function.guess (/usr/lib/atom/node_modules/github/lib/models/workdir-context.js:145:12)
    at new GithubPackage (/usr/lib/atom/node_modules/github/lib/github-package.js:145:52)
    at Proxy.initialize (/usr/lib/atom/node_modules/github/lib/index.js:12:12)
    at /usr/lib/atom/src/package.js:197:20
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at Package.module.exports.Package.initializeIfNeeded (/usr/lib/atom/src/package.js:189:12)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:246:16)
    at /usr/lib/atom/src/package.js:223:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at /usr/lib/atom/src/package.js:216:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:213:34)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:679:36)
    at config.transactAsync (/usr/lib/atom/src/package-manager.js:654:30)
    at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:365:18)
    at PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:652:17)
    at PackageManager.activate (/usr/lib/atom/src/package-manager.js:635:44)
    at /usr/lib/atom/src/atom-environment.js:848:30
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by debasishpatra** [comment]
I just opened it while screencasting., when this crash happened.
No it has not happened again till now.
Cheers.

**Comment by cbrghton** [comment]
I have the same problem but its only when I execute atom with GUI, when I execute in terminal, dont happening

**Comment by rsese** [comment]
Looks like the original reporter deleted their account - @cbrghton if you're still seeing this error, please open a new issue and fill out the issue template and we'll take a look.
