### ISSUE TITLE
Uncaught Error: GitTabController instance is not associated with a valid virtualNode. Perhaps thi...

### ISSUE THREAD

**Issue by stefee** [atom/github#1297]
Copied from [comment](https://github.com/atom/atom/issues/15855#issuecomment-361015998) in https://github.com/atom/atom/issues/15855.

### Stack Trace

Uncaught Error: GitTabController instance is not associated with a valid virtualNode. Perhaps this component was never initialized?

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:100

Error: GitTabController instance is not associated with a valid virtualNode. Perhaps this component was never initialized?
    at updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:100:17)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:72:13
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -0:17.1.0 project-plus:toggle-project-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-one-dark-ui)
  3x -0:16.7.0 core:move-down (input.hidden-input)
     -0:16 core:confirm (input.hidden-input)
     -0:15.4.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-one-dark-ui)
     -0:14.9.0 project-plus:toggle-project-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-one-dark-ui)
  2x -0:14.4.0 core:move-down (input.hidden-input)
     -0:14.1.0 core:confirm (input.hidden-input)
     -0:13.8.0 project-plus:toggle-project-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-one-dark-ui)
  5x -0:13.4.0 core:move-down (input.hidden-input)
     -0:12.7.0 core:confirm (input.hidden-input)
     -0:12.4.0 project-plus:toggle-project-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-one-dark-ui)
     -0:11.8.0 core:move-down (input.hidden-input)
     -0:11.6.0 core:confirm (input.hidden-input)
     -0:11.1.0 project-plus:toggle-project-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-one-dark-ui)
     -0:10.3.0 editor:consolidate-selections (input.hidden-input)
     -0:10.3.0 core:cancel (input.hidden-input)
```

Here is some additional context:
* Output `atom --version`:
  ```
  Atom    : 1.23.3
  Electron: 1.6.15
  Chrome  : 56.0.2924.87
  Node    : 7.4.0
  ```
* git version 2.14.3 (Apple Git-98)
* Installed packages at time of writing: https://raw.githubusercontent.com/srilq/dotfiles/4b284b5330bacb6a378001249752007a770ace99/atom.symlink/packages.txt
* Other config in `~/.atom` at time of writing: https://github.com/srilq/dotfiles/tree/4b284b5330bacb6a378001249752007a770ace99/atom.symlink

**Comment by srilq** [comment]
See this comment: https://github.com/atom/atom/issues/15855#issuecomment-367853029
and video of bug: https://drive.google.com/file/d/1Zzyh_S652FvNDJJ791UyO5ohmTrmTYM0/view
