### ISSUE TITLE
Can't properly clone a private github repo

### ISSUE THREAD

**Issue by BNasmith** [atom/github#1324]
I've been cloning private github repositories into atom for a few months now without any trouble. 

Just recently, however, when I tried to clone a new repository (via CTRL-SHIFT-P, Github Clone, and using the URL from my repository), none of the files in the repository transfer to Atom and the resulting folder won't recognize a remote master branch, as depicted below:

![untitled](https://user-images.githubusercontent.com/24949051/36651097-ed475db8-1a74-11e8-8b9c-0619e9fe6ec4.png)

I'm afraid I'm stuck. I don't have the skills to fix this myself.

**Comment by smashwilson** [comment]
Well that doesn't look right 😄 

> [..] none of the files in the repository transfer to Atom [..]

Can you elaborate on this, please? Is the repository actually on disk?

> [..] the resulting folder won't recognize a remote master branch [..]

This bit sounds like a mangled `.git/config`. I'm unsure offhand why that would happen though, although I believe I've seen it myself on Windows.

Can you confirm some additional information?

* Does the problem reproduce in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* Does this happen every time you clone, or only sometimes?
* Does it _only_ happen on private repositories?
* Can you share your Atom version? You can find this by running `atom --version` at the command line.
* What OS and version are you running?

**Comment by BNasmith** [comment]
Hello,
I'm using Atom on three different Windows computers (Win10 and Win7). The same problem occurs in each case when I try to clone my private repository from Github onto a PC hard drive, using Atom.

* Yes, I get the same problem in safe mode.
* It happens whenever I try to clone a private repository.
* It doesn't seem to be a problem with public repositories.
* My atom version is 1.24.0 
* I'm running Windows 7 Enterprise, Service Pack 1 at the moment. I have the same problem in Windows 10 on two other devices. 

A couple weeks ago I was having no problem at all. Something must have changed between now and then that affected all three devices I use. Thank you

**Comment by rsese** [comment]
While poking at this I was able to reproduce this behavior - I started by removing any saved credentials from Credential Manager.  Then I cloned a private repository from Atom with `GitHub: Clone`, a credential helper dialog popped up asking for my username/password, and I entered in my credentials.

The clone finished in Atom but there were no files, just the `.git` directory and when I clicked on the push/pull arrows, I see the same "No remote detected for branch master" message.  I did have diagnostics enabled for the package and see that it looks like the clone failed but there were no error notifications - in the output I see a "Repository not found" message in the output and the clone output ends with:

```
git-credential-atom: stdout:

git-credential-atom: stderr:
16:17:35.392899 git.c:344               trace: built-in: git 'credential' 'fill'
16:17:35.393899 run-command.c:626       trace: run_command: 'git credential-manager get'
16:17:35.525833 git.c:576               trace: exec: 'git-credential-manager' 'get'
16:17:35.526334 run-command.c:626       trace: run_command: 'git-credential-manager' 'get'
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
fatal: could not read Username for 'https://github.com': terminal prompts disabled

git-credential-atom: user-configured credential helpers failed with exit code 128. this is ok
git-credential-atom: requesting dialog through Atom socket
git-credential-atom: prompt = "Please enter your credentials for https://github.com" includeUsername = true
git-credential-atom: connection established
git-credential-atom: writing payload
git-credential-atom: payload written
```

Then I went to Git Bash and tried to clone from there - the same credential helper dialog popped up and I entered in my username/password and the clone worked fine.  I delete the clone and saw that the credentials are saved in Credential Manager.  I try cloning from Atom again and it works this time.

Not sure if this is helpful @smashwilson?

**Comment by BNasmith** [comment]
Hello, I tried cloning in Gitbash. This seemed to work fine. Then I opened atom and hit "fetch" to see if it would sync with the Github version. I then got this error popping up:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught Invariant Violation: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.

```
At C:\Users\benna\AppData\Local\atom\app-1.24.1\resources\app\node_modules\fbjs\lib\invariant.js:49

Invariant Violation: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.
    at invariant (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/fbjs/lib/invariant.js:42:21)
    at getRequest (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:42:57)
    at ReactRelayQueryRenderer._fetchForProps (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:119:27)
    at new ReactRelayQueryRenderer (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:64:46)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:295:22)
    at ReactCompositeComponentWrapper._constructComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:282:25)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:185:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at ReactCompositeComponentWrapper.performInitialMount (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:40)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at Object.updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:119:57)
    at ReactDOMComponent._reconcilerUpdateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:209:34)
    at ReactDOMComponent._updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:308:37)
    at ReactDOMComponent.updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:295:18)
    at ReactDOMComponent._updateDOMChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:944:18)
    at ReactDOMComponent.updateComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:758:16)
    at ReactDOMComponent.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:720:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at Object.updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:107:31)
```

### Commands

```
     -0:31.9.0 core:focus-next (input.input-text.github-CredentialDialog-Username)
```

### Non-Core Packages

```
atom-clock 0.1.16 
autocomplete-python 1.10.5 
Hydrogen 2.2.3 
language-latex 1.1.1 
latex 0.49.0 
latex-autocomplete 1.1.1 
markdown-preview-plus 2.5.5 
pdf-view 0.65.0 
script 3.17.3 
wordcount 2.10.4 
Zen 0.18.0 
```

**Comment by rsese** [comment]
Oh hmmm, I'm seeing that same error in devtools console by just opening a project that's a Git repo - I see it on Windows 10 with 1.24.1 and on macOS 10.12.6 with 1.26.0-dev-429f2bdd0.   Should we open a new issue for that error :point_up: @smashwilson?

@BNasmith despite the error, does the fetch succeed?  It did in my testing on Windows 10, I also successfully pulled from a private repo.

**Comment by rsese** [comment]
Oh it looks like I can't login to the GitHub panel anymore and when I do, that error pops up in console - I'll just go ahead and create a separate issue for that for now.

**Comment by BNasmith** [comment]
Hello, no it doesn't seem like the fetch succeeded. In other news, I'm still able to clone and push/fetch/pull from bash, which I didn't know how to do before.

**Comment by monroews** [comment]
I am able to clone public GitHub repositories using atom 2.3.0, but I can't clone my private repositories. It starts to clone and creates the folder, but then doesn't download any files.

I suspect this is related to a problem with Atom that it requires me to log in every time I do anything with one of my private repositories. Atom no longer saves my credentials.

**Comment by chaoming** [comment]
Same here, it doesn't pull any files from Github private repositories. Where Atom can save my credentials?

**Comment by culdo** [comment]
Same thing happening, I found that append `.git` to repo url can solve this problem, another issue is the branch indictor seemly only show master branch, not all.

**Comment by kasuke5** [comment]
Same problem here, I just download github for windows, clone my repo and after that, it propose me to open with my favorite editor 'atom' and the integrated atom github seems to see my branch and copy my files. Problem solved for me

**Comment by zatch** [comment]
I had a similar issue where cloning a private repo failed a couple times. I tried cloning a couple times before I got it working. 

The first attempt yielded the same result: empty repo with just a .git folder. I deleted the .git folder, restarted Atom, and tried again. 

On the second attempt, I got farther, but I had some strange behavior with the GitHub authentication dialog -- the dialog opened ~3-4 times and kept prompting me to enter my credentials. Eventually it worked and I was able to commit locally, but then I ran into an error pushing to GitHub. I opened `.git/config` and found that something failed while cloning -- it said `undefined` everywhere it should have said `origin`. A simple find/replace fixed this for me!

config after second clone attempt:
![image](https://user-images.githubusercontent.com/1699338/120357475-7e6ea300-c2d3-11eb-9131-a8ec08f1ae55.png)

config after replacing "undefined" with "origin":
![image](https://user-images.githubusercontent.com/1699338/120357574-98a88100-c2d3-11eb-81e1-e68de220000f.png)

All seems well now and I'm able to push to GitHub without issue.

**Comment by apicgg** [comment]
This seems to be working - 
1. Install GitHub CLI or Github desktop.
2. Clone it in the CLI (mac/linux) or desktop (windows).
3. Add that project folder into atom.

**Comment by janagyjr** [comment]
I'm having this same problem, will try what apicgg suggests. I wish Atom would get this fixed. I have issues pull/pushing to organizational repositories and cannot clone at all private ones.

**Comment by apicgg** [comment]
> I'm having this same problem, will try what apicgg suggests. I wish Atom would get this fixed. I have issues pull/pushing to organizational repositories and cannot clone at all private ones.

@janagyjr Better switch to vscode. You can use the Gitlens extention. A lot better than this.

**Comment by janagyjr** [comment]
Using Github CLI on Linux worked for me, and I've already been using Github Desktop on Windows for the organizational repo issues.

I know a lot of people who say switch to vscode. I'll check it out.
