### ISSUE TITLE
Can't commit or stage changes from the git tab.

### ISSUE THREAD

**Issue by rsese** [atom/github#1336]
_From @abhishekBM4576 on March 7, 2018 17:14_

Did every possible thing mentioned in the debugging guide and searched for FAQ but couldn't find similar issues in github or other websites.

### Description

Whenever I open a local git repository and make changes to one of the files in Atom, I can see green, yellow and red lines indicating that the file has been modified. But I can't see the branch name in the status bar and I can't view or commit changes in the git tab. It is just empty even if I've made a change or staged.

### Steps to Reproduce

1. Make a change to file in a repository.
2. Go to the git tab.
3. Commit the changes (and the current branch should be visible in the status bar).

**Expected behavior:**
Be able to commit from the git tab.

**Actual behavior:**
Doesn't show the changes and the commit button is greyed out.

### Versions

**Atom version:**
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Apm version:**
apm  1.18.12
npm  3.10.10
node 6.9.5 ia32
atom 1.24.0
python 3.6.4
git 2.14.1.windows.1

**OS version:**
Windows 7(32-bit) with service pack 1

![1](https://user-images.githubusercontent.com/30763111/37106877-dd33625a-2258-11e8-9412-6564408ec1e3.png)
![2](https://user-images.githubusercontent.com/30763111/37106911-fadf4a4e-2258-11e8-88c9-b7f996c34c95.png)
![3](https://user-images.githubusercontent.com/30763111/37106930-05d76990-2259-11e8-9093-47c68ff84ead.png)

It would be so thankful if somebody helped me out. I'm trying to feel the real power of Atom text editor and its community.

_Copied from original issue: atom/atom#16897_

**Comment by rsese** [comment]
Thanks for the report!  Do you see any errors in devtools console?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

Also, do you see this behavior with any project or just this project?

**Comment by abhishekBM4576** [comment]
Hey thanks for reacting @rsese . Now when I checked the console I saw an error related to git. I'll paste it down.

```
Uncaught (in promise) Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.execFile (child_process.js:160:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:200:20)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\dugite\build\lib\git-process.js:65:52
    at Function.exec (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\dugite\build\lib\git-process.js:48:16)
    at Proxy.executeGitCommand (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:397:42)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:244:44
    at Generator.next (<anonymous>)
    at step (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:60:191)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:60:437
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:60:99
    at Promise (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:341:26)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:242:16
    at Generator.next (<anonymous>)
    at step (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:60:191)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:60:437
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\git-shell-out-strategy.js:60:99
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:26:38
    at Generator.next (<anonymous>)
    at step (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:7:191)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:7:437
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:7:99
    at Task.execute (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:31:7)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:96:20
    at Generator.next (<anonymous>)
    at step (C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:7:191)
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:7:437
    at C:\Users\Admin\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\async-queue.js:7:99
```

This happens with all the projects even if it's not a git repo

**Comment by rsese** [comment]
Thanks for spotting that :+1:

Along with the error, you mentioned that you're on 32-bit Windows so I think you're hitting https://github.com/atom/github/issues/986.  There's a potential workaround mentioned in https://github.com/atom/github/issues/986#issuecomment-320960841 but I don't have 32-bit Windows to test with so I can't verify if it will work.

Closing as a duplicate but you can subscribe to https://github.com/atom/github/issues/986 for updates if you'd like.
