### ISSUE TITLE
Can't login to Github tab, can't push to Github, can't commit...

### ISSUE THREAD

**Issue by jaamiem** [atom/github#1354]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When trying to log in to the GitHub tab I paste the auth code and click 'login' but nothing other than errors in the console arrive.

The same happens if I try to commit except with that one a red box appears telling me that it was unable to commit.

The same happens if I try to push committed files to my repo, except with this one I get a much much much bigger error code that looks to be a duplicate of the one in the console.

This has happened on two totally unrelated computers miles from each other, one completely bare and another which was customised and had 4 packages installed and 2 open projects in the tree.

### Steps to Reproduce

1. Try login to the Github tab
2. Fail

**Expected behavior:**

Atom to work.

**Actual behavior:**

Error posts in console.

**Reproduces how often:**

100%

### Versions

Atom: 1.24.1
APM: 1.18.12
Windows 7

#### They all seem to give this same error.
Uncaught (in promise) Error: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.
    at invariant (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\fbjs\lib\invariant.js:42:21)
    at getRequest (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\relay-runtime\lib\RelayModernGraphQLTag.js:42:57)
    at ReactRelayQueryRenderer._fetchForProps (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-relay\lib\ReactRelayQueryRenderer.js:119:27)
    at new ReactRelayQueryRenderer (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-relay\lib\ReactRelayQueryRenderer.js:64:46)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:295:22)
    at ReactCompositeComponentWrapper._constructComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:282:25)
    at ReactCompositeComponentWrapper.mountComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:185:27)
    at Object.mountComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactReconciler.js:43:41)
    at ReactCompositeComponentWrapper.performInitialMount (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:368:40)
    at ReactCompositeComponentWrapper.mountComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:255:27)
    at Object.mountComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactReconciler.js:43:41)
    at Object.updateChildren (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactChildReconciler.js:119:57)
    at ReactDOMComponent._reconcilerUpdateChildren (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactMultiChild.js:209:34)
    at ReactDOMComponent._updateChildren (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactMultiChild.js:308:37)
    at ReactDOMComponent.updateChildren (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactMultiChild.js:295:18)
    at ReactDOMComponent._updateDOMChildren (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactDOMComponent.js:944:18)
    at ReactDOMComponent.updateComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactDOMComponent.js:758:16)
    at ReactDOMComponent.receiveComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactDOMComponent.js:720:16)
    at Object.receiveComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactCompositeComponent.js:558:18)
    at Object.performUpdateIfNecessary (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactReconciler.js:154:28)
    at runBatchedUpdates (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactUpdates.js:148:27)
    at ReactReconcileTransaction.perform (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactUpdates.js:87:38)
    at Object.flushBatchedUpdates (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactUpdates.js:170:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\Transaction.js:207:31)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\Transaction.js:154:22)
    at Object.batchedUpdates (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:60:32)
    at Object.enqueueUpdate (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactUpdates.js:198:28)
    at enqueueUpdate (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactUpdateQueue.js:22:22)
    at Object.enqueueSetState (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react-dom\lib\ReactUpdateQueue.js:216:11)
    at Wrapper.ReactComponent.setState (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\react\lib\ReactBaseClasses.js:62:22)
    at ModelObserver.didUpdate (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\github\lib\decorators\observe-model.js:68:26)
    at C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\github\lib\models\model-observer.js:68:23
    at Generator.next (<anonymous>)
    at step (C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\github\lib\models\model-observer.js:7:197)
    at C:\Users\Jim\AppData\Local\atom\app-1.24.1\resources\app\node_modules\github\lib\models\model-observer.js:7:367
invariant @ <embedded>:267311
getRequest @ <embedded>:311118
_fetchForProps @ <embedded>:295651
ReactRelayQueryRenderer @ <embedded>:295596
_constructComponentWithoutOwner @ <embedded>:290100
_constructComponent @ <embedded>:290087
mountComponent @ <embedded>:289990
mountComponent @ <embedded>:226960
performInitialMount @ <embedded>:290173
mountComponent @ <embedded>:290060
mountComponent @ <embedded>:226960
updateChildren @ <embedded>:307478
_reconcilerUpdateChildren @ <embedded>:287537
_updateChildren @ <embedded>:287636
updateChildren @ <embedded>:287623
_updateDOMChildren @ <embedded>:271509
updateComponent @ <embedded>:271323
receiveComponent @ <embedded>:271285
receiveComponent @ <embedded>:227039
_updateRenderedComponent @ <embedded>:290556
_performComponentUpdate @ <embedded>:290526
updateComponent @ <embedded>:290447
receiveComponent @ <embedded>:290349
receiveComponent @ <embedded>:227039
_updateRenderedComponent @ <embedded>:290556
_performComponentUpdate @ <embedded>:290526
updateComponent @ <embedded>:290447
performUpdateIfNecessary @ <embedded>:290363
performUpdateIfNecessary @ <embedded>:227071
runBatchedUpdates @ <embedded>:227230
perform @ <embedded>:274639
perform @ <embedded>:274639
perform @ <embedded>:227169
flushBatchedUpdates @ <embedded>:227252
closeAll @ <embedded>:274705
perform @ <embedded>:274652
batchedUpdates @ <embedded>:271993
enqueueUpdate @ <embedded>:227280
enqueueUpdate @ <embedded>:273704
enqueueSetState @ <embedded>:273898
ReactComponent.setState @ <embedded>:224890
didUpdate @ <embedded>:232790
(anonymous) @ <embedded>:232070
step @ <embedded>:232009
(anonymous) @ <embedded>:232009

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.25.0 when it is released.
