### ISSUE TITLE
Uncaught (in promise) TypeError: pendingItem.getWorkingDirectory is not a function

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1396]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

![github pending console error](https://user-images.githubusercontent.com/1058982/38922487-917af6f0-42f8-11e8-82f5-79eee7223ff7.gif)

```
Uncaught (in promise) TypeError: pendingItem.getWorkingDirectory is not a function
    at props.workspace.getPanes.filter.pane (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:589:48)
    at Array.filter (native)
    at StagingView.getPanesWithStalePendingFilePatchItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:582:50)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:547:60
    at Generator.next (<anonymous>)
    at step (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:83:197)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:83:443
    at Promise (<anonymous>)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:83:105
    at StagingView.didSelectSingleItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:576:13)
    at StagingView.didChangeSelectedItems (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:529:18)
    at setTimeout (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:136:23)
```

### Steps to Reproduce

1. Open Atom in safe mode from `cmd.exe` using `.\atom --safe`
1. Open a git repository that contains two files `foo.txt` and `bar.txt`
1. Make changes to `foo.txt`
1. Open `foo.txt` in the left pane in a pending state
1. Open an untitled editor in the right pane
1. Focus the right pane
1. Stage `foo.txt`

**Expected behavior:**

No error in the console

**Actual behavior:**

Error thrown in the console

**Reproduces how often:**

100%

### Versions

Atom    : 1.28.0-dev-603dc5a05
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by smashwilson** [comment]
@Ben3eeE are you running atom/github from master? This looks related to #1390, but that hasn't been included in a tagged release yet.

**Comment by Ben3eeE** [comment]
@smashwilson Running a master build from this morning. I do have `fuzzy-finder` and `tree-view` linked but not `github`. So this should be github@0.14.0.

**Comment by smashwilson** [comment]
Gotcha. Just checking 👍
