### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'quietlySelectItem' of undefined

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1399]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Right click on a file and choose `view staged changes` or `view unstaged changes`

![github unstaged changes error](https://user-images.githubusercontent.com/1058982/38989046-caf4205e-43d5-11e8-8216-ed3344958c96.gif)

```
Uncaught (in promise) TypeError: Cannot read property 'quietlySelectItem' of undefined
    at GitTabController.quietlySelectItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\controllers\git-tab-controller.js:470:34)
    at RootController.quietlySelectItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\controllers\root-controller.js:603:72)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\controllers\root-controller.js:649:22
    at Generator.next (<anonymous>)
    at step (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\controllers\root-controller.js:138:197)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\controllers\root-controller.js:138:367
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Steps to Reproduce

1. Open Atom in safe mode `.\atom --safe` from `cmd.exe` in `atom/atom`
2. Open `application-delegate.js`
3. Right click on the file and pick view staged changes or view unstaged changes

**Note:** Same exception appears if you do this even where there are staged or unstaged changes.

**Expected behavior:**

Nothing to happen or a message that there are no staged or unstaged changes because there are none.

**Actual behavior:**

Exception in the console

**Reproduces how often:**

100%

### Versions

Atom : 1.28.0-dev-603dc5a05
Electron: 1.7.11
Chrome : 58.0.3029.110
Node : 7.9.0

### Additional Information

Related to https://github.com/atom/github/issues/951 which is an exception when trying to view staged/unstaged changes on untitled buffers.

**Comment by dwelle** [comment]
:+1:  any date on release of this fix?

**Comment by Ben3eeE** [comment]
@dwelle The fix for this issue is currently scheduled to be included in the next beta hotfix.

**Comment by dwelle** [comment]
No backport to stable? Will need to downgrade atom from zip file otherwise, since this bug makes this package very hard to use.

**Comment by smashwilson** [comment]
> No backport to stable?

I didn't actually know this affected stable 😅 

I've backported the fix to the 0.12 release line in 6b62f9c8586ed79. I don't know if we're planning to do another hotfix of Atom 1.26 or not, but if we do it'll be there.
