### ISSUE TITLE
Uncaught (in promise) TypeError: _this.activeFilePatch.getFilePath is not a function

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1406]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

![github split unstaged changes](https://user-images.githubusercontent.com/1058982/39042950-788904da-448c-11e8-9b9d-effa85cf32ff.gif)

```
Uncaught (in promise) TypeError: _this.activeFilePatch.getFilePath is not a function
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:256:61
    at Generator.next (<anonymous>)
    at step (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:83:197)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:83:443
    at Promise (<anonymous>)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:83:105
    at StagingView.update (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\staging-view.js:268:13)
    at EtchWrapper.updateComponent (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\etch-wrapper.js:155:33)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\etch-wrapper.js:85:27
    at Generator.next (<anonymous>)
    at step (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\etch-wrapper.js:24:197)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\etch-wrapper.js:24:443
    at Promise (<anonymous>)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\etch-wrapper.js:24:105
    at EtchWrapper.componentDidUpdate (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\etch-wrapper.js:93:13)
    at CallbackQueue.notifyAll (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\CallbackQueue.js:74:28)
    at ReactReconcileTransaction.close (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactReconcileTransaction.js:78:32)
    at ReactReconcileTransaction.closeAll (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\Transaction.js:207:31)
    at ReactReconcileTransaction.perform (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\Transaction.js:154:22)
    at ReactUpdatesFlushTransaction.perform (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdates.js:87:38)
    at flushBatchedUpdates (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdates.js:170:25)
    at ReactUpdatesFlushTransaction.close (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdates.js:45:13)
    at ReactUpdatesFlushTransaction.closeAll (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\Transaction.js:207:31)
    at ReactUpdatesFlushTransaction.perform (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\Transaction.js:154:22)
    at ReactUpdatesFlushTransaction.perform (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdates.js:87:38)
    at Object.flushBatchedUpdates (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdates.js:170:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\Transaction.js:207:31)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\Transaction.js:154:22)
    at Object.batchedUpdates (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:60:32)
    at Object.enqueueUpdate (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdates.js:198:28)
    at enqueueUpdate (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdateQueue.js:22:22)
    at Object.enqueueElementInternal (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactUpdateQueue.js:223:11)
    at C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactMount.js:285:30
    at Object.scrollMonitor (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactMount.js:273:11)
    at Object._updateRootComponent (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactMount.js:284:22)
    at Object._renderSubtreeIntoContainer (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactMount.js:372:26)
    at Object.render (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\react-dom\lib\ReactMount.js:420:29)
    at GithubPackage.rerender (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\github-package.js:367:30)
    at GithubPackage.removeFilePatchItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\github-package.js:503:18)
    at RootController.removeFilePatchItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\controllers\root-controller.js:486:29)
    at subscriptions.props.workspace.onDidDestroyPaneItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\github\lib\views\pane-item.js:100:26)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PaneContainer.didDestroyPaneItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\src\pane-container.js:280:24)
    at Pane.removeItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\src\pane.js:707:56)
    at Pane.destroyItem (C:\Users\lineri\Desktop\issues\atom_master\atom\out\Atom x64\resources\app\src\pane.js:783:16)
    at <anonymous>
```

### Steps to Reproduce

1. Open Atom in safe mode `.\atom --safe` from `cmd.exe`
2. Make changes to `foo.txt` and open the unstaged changes tab
3. Split the unstaged changes tab right
4. Close the split unstaged changes tab

**Expected behavior:**

The tab to close without error

**Actual behavior:**

Exception in the console

**Reproduces how often:**

100%

### Versions

Atom : 1.28.0-dev-603dc5a05
Electron: 1.7.11
Chrome : 58.0.3029.110
Node : 7.9.0

**Comment by smashwilson** [comment]
I've fixed this on `0.14-releases` so it'll go out with the next Atom hotfix on stable if we do one. In the meantime, splitting file patch pane items is broken in a _different_ way on master, so I'll fix that presently.

**Comment by smashwilson** [comment]
Backported to `0.12-releases` for Atom stable.

**Comment by smashwilson** [comment]
Okay, fixed on master, beta and stable.
