### ISSUE TITLE
Uncaught (in promise) peg$SyntaxError {message: "Expected "@@ -" or "@@@ -" but end of input found."

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1409]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

![github resolve as theirs](https://user-images.githubusercontent.com/1058982/39077076-82bfbdf4-44ff-11e8-88e9-3719d2e65aba.gif)

```
Uncaught (in promise) peg$SyntaxError {message: "Expected "@@ -" or "@@@ -" but end of input found.", expected: Array(2), found: null, location: Object, name: "SyntaxError"…}expected: Array(2)found: nulllocation: Objectmessage: "Expected "@@ -" or "@@@ -" but end of input found."name: "SyntaxError"rawStack: Array(8)stack: "SyntaxError: Expected "@@ -" or "@@@ -" but end of input found.↵    at peg$buildStructuredError (C:\Users\bene\AppData\Local\atom\app-1.27.0-beta0\resources\app\node_modules\what-the-diff\lib\parser.js:381:18)↵    at Object.peg$parse [as parse] (C:\Users\bene\AppData\Local\atom\app-1.27.0-beta0\resources\app\node_modules\what-the-diff\lib\parser.js:1938:17)↵    at parse (C:\Users\bene\AppData\Local\atom\app-1.27.0-beta0\resources\app\node_modules\what-the-diff\index.js:5:25)↵    at C:\Users\bene\AppData\Local\atom\app-1.27.0-beta0\resources\app\node_modules\github\lib\git-shell-out-strategy.js:714:49↵    at Generator.next (<anonymous>)↵    at step (C:\Users\bene\AppData\Local\atom\app-1.27.0-beta0\resources\app\node_modules\github\lib\git-shell-out-strategy.js:104:197)↵    at C:\Users\bene\AppData\Local\atom\app-1.27.0-beta0\resources\app\node_modules\github\lib\git-shell-out-strategy.js:104:367↵    at <anonymous>"__proto__: Error
step @ <embedded>:186613
(anonymous) @ <embedded>:186613
00:59:40.062 <embedded>:186613 Uncaught (in promise) peg$SyntaxError {message: "Expected "@@ -" or "@@@ -" but end of input found.", expected: Array(2), found: null, location: Object, name: "SyntaxError"…}
step @ <embedded>:186613
(anonymous) @ <embedded>:186613
```

### Steps to Reproduce

1. Undo discard resulting in merge conflicts
1. In the Git tab right click and resolve as theirs

**Expected behavior:**

Resolving as theirs without error

**Actual behavior:**

Several errors repeated in the console

**Reproduces how often:**

100%

### Versions

Atom    : 1.27.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by smashwilson** [comment]
I'm having trouble reproducing this on master or 0.14-releases. Maybe it has something to do with the nature of the actual patch?

**Comment by Ben3eeE** [comment]
Hmm. I had it reproduce for several different small patches. I'll poke at it again to see if I can narrow it down further and provide more detailed steps :sparkles:
