### ISSUE TITLE
Uncaught TypeError: this.refCommitButton.focus is not a function

### ISSUE THREAD

**Issue by bryant-sfdo** [atom/github#1416]
[Enter steps to reproduce:]

1. resolve a bunch of merge conflicts
2. After all files are resolved, click commit and saw the following error.

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [github](https://github.com/atom/github) package 0.14.0

### Stack Trace

Uncaught TypeError: this.refCommitButton.focus is not a function

```
At /Users/bung/git/atom_stuff/github/lib/views/commit-view.js:558

TypeError: this.refCommitButton.focus is not a function
    at CommitView.setFocus (/Users/bung/git/atom_stuff/github/lib/views/commit-view.js:558:30)
    at CommitController.setFocus (/Users/bung/git/atom_stuff/github/lib/controllers/commit-controller.js:242:31)
    at GitTabView.setFocus (/Users/bung/git/atom_stuff/github/lib/views/git-tab-view.js:243:36)
    at Proxy.restoreFocus (/Users/bung/git/atom_stuff/github/lib/controllers/git-tab-controller.js:405:18)
    at process.nextTick (/Users/bung/git/atom_stuff/github/lib/controllers/git-tab-controller.js:414:31)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
  3x -0:18.1.0 github:resolve-file-as-ours (span.github-RemainingConflicts.text-warning)
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
ide-java 0.8.2 
language-gherkin 1.0.4 
snippet-generator 0.3.2 
Sublime-Style-Column-Selection 1.7.4 
teletype 0.13.0 
```

**Comment by smashwilson** [comment]
Okay, I can't reproduce on 223920b8db80e, the current tip of `0.14-releases`. I suspect you have atom/github installed from git and are tracking master, or that your Atom installation is built from master. In either case the fix on master should be sufficient :+1:
