### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1443]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

**Note:** Running atom/github master

When opening Atom in a project with untitled pane items an exception is thrown:

```
C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:151 TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at URIPattern.matches (C:/Users/lineri/.atom/packages/github/lib/atom/uri-pattern.js:61:23)
    at PaneItem.currentlyOpen.props.workspace.getPaneItems.reduce (C:/Users/lineri/.atom/packages/github/lib/atom/pane-item.js:47:48)
    at Array.reduce (native)
    at new PaneItem (C:/Users/lineri/.atom/packages/github/lib/atom/pane-item.js:45:8)
    at constructClassInstance (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:111:81)
    at beginWork (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:138:154)
    at e (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:176:105)
    at f (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:176:379)
    at G (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:182:329)
    at x (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:181:378)
    at n (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:181:221)
    at B (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:180:117)
    at v (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:179:51)
    at b (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:190:302)
    at Object.updateContainer (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:191:389)
    at tg.render (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:228:368)
    at C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:242:475
    at Object.unbatchedUpdates (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:188:42)
    at Eg (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:242:394)
    at Object.render (C:\Users\lineri\.atom\packages\github\node_modules\react-dom\cjs\react-dom.production.min.js:244:189)
    at GithubPackage.rerender (C:/Users/lineri/.atom/packages/github/lib/github-package.js:267:14)
    at GithubPackage.activate (C:/Users/lineri/.atom/packages/github/lib/github-package.js:237:10)
    at <anonymous>
```

### Steps to Reproduce

1. `apm install atom/github`
1. Open Atom in a project folder
1. Open an untitled buffer and add some text to it
1. Reload Atom

**Expected behavior:**

That the package works. No errors in the console.

**Actual behavior:**

Exception in the console. Package doesn't work.

**Reproduces how often:**

100%

### Versions

Atom 1.28.0-dev-a3631f0da
GitHub-package@https://github.com/atom/github/commit/8b0226d01a85db52c1634d9844241e0b0d46e082

**Comment by smashwilson** [comment]
Good catch 👍 Just a bad assumption on my part.

**Comment by Ben3eeE** [comment]
Thanks for the quick fix :bowing_man: Updated and confirmed that it's working now. I'll keep running on master to see if I encounter any more issues :slightly_smiling_face:

**Comment by smashwilson** [comment]
Can you try now? #1448 should take care of that one. 😅
