### ISSUE TITLE
Discard change not working / locking file on Windows 10

### ISSUE THREAD

**Issue by ryanolsonx** [atom/github#1486]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? [X]
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? [X]
* Have you checked the FAQs on the [message board][message-board] for common solutions? [X]
* Have you checked that your issue [isn't already filed][already-filed]? [X]

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

In a git repository, after making modifications to a file, when attempting to discard change, the file gets locked (can't open for read and cannot run `git checkout -- c:\path\to\file`) and it does not revert the change.  In order to get out of this situation, a user must completely exit out of Atom before getting back in and having full access to their file again. At this point, in my experience, the file is still not reverted and I end up running `git checkout -- c:\path\to\file`.

### Steps to Reproduce

1. Initialize git repository for testing (`mkdir github-issue && cd github-issue && git init`).
2. Create file in repository and commit as initial commit (`echo hello > README.md && git add . && git commit -m "Initial Commit"`).
3. Open Atom and make modification to `Readme.md` in Atom before closing pane.
4. Open up the Git tab.
5. Right click on `Readme.md` and select "Discard Changes."
6. At this point, you'll see the file still in the "Unstaged Changes" list.
7. Attempt to open `Readme.md` again and see error message "EPERM: operation not permitted, open "C:\github-issue\Readme.md""
8. Go to command prompt and run `git checkout -- c:\github-issue\Readme.md` and get error message "Unlink of file 'README.md' failed. Should I try again? (y/n)"
9. Exit all atom instances and run the command again, you'll see that it reverts properly.

**Expected behavior:**

A simple discard of modification to `Readme.md`.

**Actual behavior:**

File gets locked and sometimes deleted while trying to discard changes on a file with modifications. It is unable to discard changes on it.

**Reproduces how often:**

Discard not working: 💯 
File gets deleted: sometimes (I don't know solid steps for that scenario)

### Versions

`atom --version`:

`Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0`

`apm --version`:
`apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 2.7.14
git 2.17.0.windows.1
visual studio 2015`

OS: Windows 10 64 Bit

**Comment by ryanolsonx** [comment]
I figured out how to reproduce the deleted file issue.

1) Create repository as above.
2) Run through the steps above to commit Readme.md and attempt to discard Readme.md
3) Instead of going to command line, re-open atom and you'll see that the Readme.md shows up in deleted status

**Comment by ryanolsonx** [comment]
I notice this error in my atom developer console.

Uncaught (in promise) GitError: git checkout -- README.md in C:\github-issue exited with code 255
stdout: 
stderr: error: unable to create file README.md: Permission denied

    at new GitError (C:/github/lib/git-shell-out-strategy.js:33:18)
    at Promise (C:/github/lib/git-shell-out-strategy.js:305:23)
    at <anonymous>

**Comment by ryanolsonx** [comment]
That seemed to work for me. Really frustrating though. Any way other users can find a resolution for this if they see the same issue?
