### ISSUE TITLE
Unable to connect to github through github pane / package in Ubuntu 18 (login to github after token does not work nor react) 

### ISSUE THREAD

**Issue by gbelbe** [atom/github#1493]
### Description
When I want to connect to a github repository, through the github Package Tab, I paste the token and press the button "login": nothing happens. 

I follow the indications:
Step 1 : go to the link to generate the authentication token
Step 2: paste the link and press "Login"

As I press Login nothing happens. (after many tries) : I opened the javascript console and paste what happen when I click on the button (find the debug info below)

### Versions
os: linux ubuntu 18.04 lts 64 bits
Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Log from Console when I click on the Login Button:

`Uncaught (in promise) Error: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.
    at invariant (/opt/atom/resources/app/node_modules/fbjs/lib/invariant.js:42:21)
    at getRequest (/opt/atom/resources/app/node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:42:57)
    at ReactRelayQueryRenderer._fetchForProps (/opt/atom/resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:119:27)
    at new ReactRelayQueryRenderer (/opt/atom/resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:64:46)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:295:22)
    at ReactCompositeComponentWrapper._constructComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:282:25)
    at ReactCompositeComponentWrapper.mountComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:185:27)
    at Object.mountComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at ReactCompositeComponentWrapper.performInitialMount (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:40)
    at ReactCompositeComponentWrapper.mountComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:27)
    at Object.mountComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at Object.updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:119:57)
    at ReactDOMComponent._reconcilerUpdateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:209:34)
    at ReactDOMComponent._updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:308:37)
    at ReactDOMComponent.updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:295:18)
    at ReactDOMComponent._updateDOMChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:944:18)
    at ReactDOMComponent.updateComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:758:16)
    at ReactDOMComponent.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:720:16)
    at Object.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at Object.updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:107:31)
    at ReactDOMComponent._reconcilerUpdateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:209:34)
    at ReactDOMComponent._updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:308:37)
    at ReactDOMComponent.updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:295:18)
    at ReactDOMComponent._updateDOMChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:944:18)
    at ReactDOMComponent.updateComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:758:16)
    at ReactDOMComponent.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:720:16)
    at Object.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at Object.updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:107:31)
    at ReactDOMComponent._reconcilerUpdateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:209:34)
    at ReactDOMComponent._updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:308:37)
    at ReactDOMComponent.updateChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:295:18)
    at ReactDOMComponent._updateDOMChildren (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:944:18)
    at ReactDOMComponent.updateComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:758:16)
    at ReactDOMComponent.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:720:16)
    at Object.receiveComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:558:18)
    at Object.performUpdateIfNecessary (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:154:28)
    at runBatchedUpdates (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:148:27)
    at ReactReconcileTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at ReactUpdatesFlushTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:87:38)
    at Object.flushBatchedUpdates (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:170:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:207:31)
    at ReactDefaultBatchingStrategyTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:154:22)
    at Object.batchedUpdates (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:32)
    at Object.enqueueUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:198:28)
    at enqueueUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:22:22)
    at Object.enqueueSetState (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:216:11)
    at ObserveModel.ReactComponent.setState (/opt/atom/resources/app/node_modules/react/lib/ReactBaseClasses.js:62:22)
    at ObserveModel.didUpdate (/opt/atom/resources/app/node_modules/github/lib/views/observe-model.js:79:18)
    at /opt/atom/resources/app/node_modules/github/lib/models/model-observer.js:68:23
    at Generator.next (<anonymous>)
    at step (/opt/atom/resources/app/node_modules/github/lib/models/model-observer.js:7:197)
    at /opt/atom/resources/app/node_modules/github/lib/models/model-observer.js:7:367
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by rsese** [comment]
Thanks for the report!

> Atom : 1.24.1

This is fixed as of 1.25 I believe so if you update to the latest release version of Atom (currently 1.27.1), that should get you past this error.
