### ISSUE TITLE
Atom will not display changes tab when clicking on changed files

### ISSUE THREAD

**Issue by Kryten0807** [atom/github#1567]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

New install of Atom 1.28.1 on a new install of Ubuntu 18.04.

It worked fine yesterday - I made commits to several projects without issue. I left Atom running overnight (as I always do). This morning, when I click on a file in either the "Unstaged Changes" or "Staged Changes" pane, the tab which shows changes to the files no longer opens.

I have tried it:
+ in safe mode
+ after clearing window state
+ with the `--disable-gpu` flag
+ after resetting to factory defaults
+ after removing and reinstalling atom.

I have also tried disabling and re-enabling the git package and in both existing git repositories and in a brand new one.

There are no messages in the console.

### Versions

atom --version
Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.1
python 2.7.15rc1
git 2.17.1

**Comment by Kryten0807** [comment]
I was (briefly) able to get it working by uninstalling (`apt-get remove --purge atom`), then re-installing from the repository as shown [here](https://flight-manual.atom.io/getting-started/sections/installing-atom/). However, as soon as I copied my configuration back to the `~/.atom` directory, it failed again.

After purging & reinstalling again, it simply is not working.

Only by rolling back to 1.27.2 did it fix the problem.

**Comment by Akimkin** [comment]
Experiencing same issue after upgrate to 1.28.1 from older version (don't remember which one exactly, probably 1.26-1.27). 

Getting following error message when right-clicking inside text area selecting to "View unstaged changes"
from the context menu:

`commitCommentContainer_item.graphql.js:112 Uncaught (in promise) TypeError: c.quietlySelectItem is not a function
    at refGitTabController.map.c (/media/storage-1/Software/atom-amd64/resources/app/node_modules/github/lib/controllers/root-controller.js:545:22)
    at RefHolder.map (/media/storage-1/Software/atom-amd64/resources/app/node_modules/github/lib/models/ref-holder.js:100:20)
    at RootController.quietlySelectItem (/media/storage-1/Software/atom-amd64/resources/app/node_modules/github/lib/controllers/root-controller.js:544:43)
    at RootController.viewChangesForCurrentFile (/media/storage-1/Software/atom-amd64/resources/app/node_modules/github/lib/controllers/root-controller.js:580:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by Akimkin** [comment]
Sorry, my previous comment seems unrelated to this issue but rather a duplicate of #1559 .
While that problem is fixed for 1.29.0 beta 1, the issue reported by OP is still there.
