### ISSUE TITLE
React 16.4.1 cannot be snapshotted

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1584]
It looks like React 16.4.1 breaks Atom's snapshot generation:

```
Verifying if snapshot can be executed via `mksnapshot`
/Users/distiller/atom/out/startup.js:187705
      var ce="function"===typeof requestAnimationFrame?requestAnimationFrame:void 0,de=Date,ee=setTimeout,fe=clearTimeout,ge=void 0;if("object"===typeof performance&&"function"===typeof performance.now){var he=performance;ge=function(){return he.now()}}else ge=function(){return de.now()};var ie=void 0,je=void 0;
                                                                                               ^

ReferenceError: setTimeout is not defined
    at Object.../node_modules/react-dom/cjs/react-dom.production.min.js (/Users/distiller/atom/out/startup.js:187705:96)
    at customRequire (/Users/distiller/atom/out/startup.js:94:47)
    at Object.../node_modules/react-dom/index.js (/Users/distiller/atom/out/startup.js:104643:26)
    at customRequire (/Users/distiller/atom/out/startup.js:94:47)
    at Object.../node_modules/github/lib/github-package.js (/Users/distiller/atom/out/startup.js:51899:23)
    at customRequire (/Users/distiller/atom/out/startup.js:94:47)
    at Object.../node_modules/github/lib/index.js (/Users/distiller/atom/out/startup.js:14078:28)
    at customRequire (/Users/distiller/atom/out/startup.js:94:47)
    at Object.<anonymous> (/Users/distiller/atom/out/startup.js:148:11)
    at Object.../src/initialize-application-window.js (/Users/distiller/atom/out/startup.js:235:10)
```

It looks like react-dom@16.4.1 references `setTimeout` in the top-level package to give it a shortened alias, which confuses electron-link, while react-dom@16.4.0 only did so within function definitions, which did not.

@maxbrunsfeld @as-cii

**Comment by maxbrunsfeld** [comment]
I wonder if it would be possible for `electron-link` to generate a lazy function getter for `ee`, since it is an alias for `setTimeout`. Unfortunately, it is defined via `var` and not `const`, so we'd have to verify that it is never assigned to again.

**Comment by annthurium** [comment]
we are on react 16.8.3 now so I'm assuming this is no longer a problem.  Feel free to reopen if it is! 😄
