### ISSUE TITLE
Stage all and Unstage all not working

### ISSUE THREAD

**Issue by adriangzz** [atom/github#1801]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    *  Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    *  Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I click on Stage All, Unstage All, right click a file and click stage, nothing happens.
In console I get this error:
`VM22 <embedded>:14 Uncaught (in promise) Error: EINVAL: invalid argument, `

### Steps to Reproduce

1. Open Git on the sidebar
2. Click on Stage all, Unstage All, right click a file -> Stage

**Expected behavior:** [What you expect to happen]

For my files to move to Staged Changes or Unstaged changes

**Actual behavior:** [What actually happens]

Files don't move.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
Windows: 10

### Additional Information

When I do apm --version I get this:
`internal/child_process.js:323`
   ` throw errnoException(err, 'spawn');`
    `^`

`Error: spawn UNKNOWN`
    `at _errnoException (util.js:1024:11)`
    `at ChildProcess.spawn (internal/child_process.js:323:11)`
    `at exports.spawn (child_process.js:502:9)`
    `at EventEmitter.<anonymous> (C:\Users\Adrian\AppData\Local\atom\app-1.32.2\resources\app\apm\lib\apm-cli.js:169:17)`
    `at _combinedTickCallback (internal/process/next_tick.js:131:7)`
    `at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by rsese** [comment]
Thanks for the report!   I was unable to reproduce on macOS 10.12.6 with Atom 1.32.2.

Do you see this behavior with any project or just the one you're working on?

And can you reproduce with any file for the "right click a file -> Stage" step?  Also for this step, are there any special characters in the filename or path of the file that you right-click to stage?

> When I do apm --version I get this:

I think you'll get that error if you run `apm --version` in Git Bash or Cygwin (/cc https://github.com/atom/apm/issues/725).  It *should* work in cmd.exe or PowerShell.

**Comment by adriangzz** [comment]
> Do you see this behavior with any project or just the one you're working on?
Yes, this behavior happens on every project.

> And can you reproduce with any file for the "right click a file -> Stage" step? 
Yes, this behavior also happens when I right click a file and click stage.

> Also for this step, are there any special characters in the filename or path of the file that you right-click to stage?
That is interesting, there are no special characters in the filename or path but I created a folder on the root of my C: drive and stage/unstage worked.

**Comment by rsese** [comment]
Ohh sorry, I just realized that I misinterpreted your repro steps.  I thought this was a series of steps:

> 2. Click on Stage all, Unstage All, right click a file -> Stage

But I think you meant that none of those functions work for you?

I played around with things more so I'll leave some notes here, tested on Windows 10 with Atom 1.32.2.

1. Started by plugging in a flash drive to use as my D: drive\
2. In Git Bash, I created a test directory `mkdir test-gh; cd test-gh`
3. Added a file `echo "Hello World" >> README.md`
4. `atom .`

At this point I found that if I open the Git panel I see the "Unsupported directory" + "Atom does not support managing Git repositories in your home or root directories" message, so you can't initialize a repo from the Git panel.

But then if I do a `git init` and an initial commit in Git Bash:

1. `git init`
2. `git add README.md`
3. `git commit -m "Initial commit"`
4. Reload Atom

After reloading Atom, the Git panel shows up normally.  If I make and save a change, it shows up in `Unstaged Changes` and at this point, if I right-click and `Stage` the file, that works ok and I can commit that change.

But where it seems to break is if I click `Stage All`, I see a "Uncaught (in promise) Error: EINVAL: invalid argument, read` message in devtools console.  At this point I can no longer right-click to stage a change unless I reload/restart Atom.

The "Atom does not support managing Git repositories in your home or root directories" doesn't seem right since I've created a subdirectory under `D:`?  Then the other issue seems to be the error from `Stage All` which then prevents things from working while right-clicking to stage a single file works.

**Comment by asdasd-123** [comment]
Sorry if its wrong to re-open this but I believe I have the same issue as OP.

I've included a video of the same thing happening (also on D:\\ which also happens to be a thumb-drive). Please let me know what other information I need to supply.
Not sure if related, but deleting files in atom never works on a thumb-drive because it fails to find the recycling bin

**Comment by rsese** [comment]
> Not sure if related, but deleting files in atom never works on a thumb-drive because it fails to find the recycling bin

That behavior is a separate issue, see and https://github.com/atom/tree-view/issues/856#issuecomment-357325782 in particular for more details.

**Comment by zmilkman** [comment]
> > Do you see this behavior with any project or just the one you're working on?
> 
> Yes, this behavior happens on every project.
> 
> > And can you reproduce with any file for the "right click a file -> Stage" step?
> 
> Yes, this behavior also happens when I right click a file and click stage.
> 
> > Also for this step, are there any special characters in the filename or path of the file that you right-click to stage?
> 
> That is interesting, there are no special characters in the filename or path but I created a folder on the root of my C: drive and stage/unstage worked.
> 
> It seems like when a folder is on D: this behavior happens, but when I move them to C: they seem to work. What can be the cause of this?

Looks like this is still open. Was there ever a solution? I get the same error.

**Comment by adriangzz** [comment]
> > > Do you see this behavior with any project or just the one you're working on?
> > 
> > 
> > Yes, this behavior happens on every project.
> > > And can you reproduce with any file for the "right click a file -> Stage" step?
> > 
> > 
> > Yes, this behavior also happens when I right click a file and click stage.
> > > Also for this step, are there any special characters in the filename or path of the file that you right-click to stage?
> > 
> > 
> > That is interesting, there are no special characters in the filename or path but I created a folder on the root of my C: drive and stage/unstage worked.
> > It seems like when a folder is on D: this behavior happens, but when I move them to C: they seem to work. What can be the cause of this?
> 
> Looks like this is still open. Was there ever a solution @adriangzz ? I get the same error.

I ended up moving my working folder to the C: drive.
