### ISSUE TITLE
Stack trace when doing a merge via CLI

### ISSUE THREAD

**Issue by smashwilson** [atom/github#2013]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When initiating a merge from the command line, the github package crashes with the following stack:

<details>

```
TypeError: Cannot read property 'split' of null
    at Diff.l.tokenize (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:1079009)
    at Diff.diff (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:1075657)
    at Object.diffLines (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:1078582)
    at transact (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:11:487130)
    at TextBuffer.transact (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:11:491885)
    at TextBuffer.setTextViaDiff (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:11:487086)
    at CommitController.componentDidUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:4185601)
    at Xh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2441204)
    at Rh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2437643)
    at Uh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2437101)
    at Sh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2436927)
    at wh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2436300)
    at kg (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2435547)
    at Object.enqueueSetState (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2411138)
    at ObserveModel.F.setState (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2337007)
    at ObserveModel.didUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:3375705)
    at ModelObserver._refreshModelData (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:3750538)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Tg @ <embedded>:14
<embedded>:14 Uncaught (in promise) TypeError: Cannot read property 'split' of null
    at Diff.l.tokenize (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:1079009)
    at Diff.diff (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:1075657)
    at Object.diffLines (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:1078582)
    at transact (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:11:487130)
    at TextBuffer.transact (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:11:491885)
    at TextBuffer.setTextViaDiff (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:11:487086)
    at CommitController.componentDidUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:4185601)
    at Xh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2441204)
    at Rh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2437643)
    at Uh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2437101)
    at Sh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2436927)
    at wh (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2436300)
    at kg (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2435547)
    at Object.enqueueSetState (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2411138)
    at ObserveModel.F.setState (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:2337007)
    at ObserveModel.didUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:3375705)
    at ModelObserver._refreshModelData (C:\Users\<user>\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:14:3750538)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

</details>

[Description of the issue]

### Steps to Reproduce

1. Open Atom
2. Initiate a merge:
   ```
   git merge feature/some-feature -m "Finish feature/some-feature
   >
   > Changes:
   > $(git log --reverse --pretty='format:- %s' release/x.y..feature/some-feature)"
   ```

**Expected behavior:**

No exceptions to be raised.

**Actual behavior:**

An exception is raised and the package crashes.

**Reproduces how often:**

Unknown. It likely depends on the nature of the merge.

### Versions

_TODO_

### Additional Information

cc @JSn1nj4

**Comment by JSn1nj4** [comment]
Version is 1.35.0.

I'm running Windows 10 64-bit version 1803 (build 17134.590, in case you need that).

**Comment by JSn1nj4** [comment]
More info: it happened just now while just running `git merge other-branch` with no flags or additional arguments. Also, I've only set up Git to open an editor when merging to `master`. I otherwise let merges follow the normal `--no-ff` workflow without a message.

<details><summary>Another stack trace</summary>
<p>

##### Extra details this time

```
VM22 <embedded>:14 TypeError: Cannot read property 'split' of null
    at Diff.l.tokenize (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1079009)
    at Diff.diff (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1075657)
    at Object.diffLines (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1078582)
    at transact (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:487130)
    at TextBuffer.transact (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:491885)
    at TextBuffer.setTextViaDiff (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:487086)
    at CommitController.componentDidUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:4185601)
    at Xh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2441204)
    at Rh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2437643)
    at Uh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2437101)
    at Sh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2436927)
    at wh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2436300)
    at kg (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2435547)
    at Object.enqueueSetState (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2411138)
    at ObserveModel.F.setState (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2337007)
    at ObserveModel.didUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:3375705)
    at ModelObserver._refreshModelData (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:3750538)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Tg	@	VM22 <embedded>:14
n.callback	@	VM22 <embedded>:14
Rf	@	VM22 <embedded>:14
Sf	@	VM22 <embedded>:14
Xh	@	VM22 <embedded>:14
Rh	@	VM22 <embedded>:14
Uh	@	VM22 <embedded>:14
Sh	@	VM22 <embedded>:14
wh	@	VM22 <embedded>:14
kg	@	VM22 <embedded>:14
enqueueSetState	@	VM22 <embedded>:14
F.setState	@	VM22 <embedded>:14
didUpdate	@	VM22 <embedded>:14
_refreshModelData	@	VM22 <embedded>:14
_tickCallback	@	internal/process/next_tick.js:188
async function (async)		
_refreshModelData	@	VM22 <embedded>:14
refreshModelData	@	VM22 <embedded>:14
_refreshModelData	@	VM22 <embedded>:14
_tickCallback	@	internal/process/next_tick.js:188
async function (async)		
_refreshModelData	@	VM22 <embedded>:14
refreshModelData	@	VM22 <embedded>:14
e.activeModel.activeModelUpdateSubscription.e.onDidUpdate	@	VM22 <embedded>:14
simpleDispatch	@	VM22 <embedded>:11
emit	@	VM22 <embedded>:11
didUpdate	@	VM22 <embedded>:14
invalidateCacheAfterFilesystemChange	@	VM22 <embedded>:14
observeFilesystemChange	@	VM22 <embedded>:14
Repository.(anonymous function)	@	VM22 <embedded>:14
WorkdirContext.subs.add.observer.onDidChange.e	@	VM22 <embedded>:14
simpleDispatch	@	VM22 <embedded>:11
emit	@	VM22 <embedded>:11
didChange	@	VM22 <embedded>:14
currentFileWatcher.t	@	VM22 <embedded>:14
onNativeEvents	@	VM22 <embedded>:14
t.native.onDidChange.t	@	VM22 <embedded>:14
simpleDispatch	@	VM22 <embedded>:11
emit	@	VM22 <embedded>:11
onEvents	@	VM22 <embedded>:14
watcher.e	@	VM22 <embedded>:14

VM22 <embedded>:14 Uncaught (in promise) TypeError: Cannot read property 'split' of null
    at Diff.l.tokenize (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1079009)
    at Diff.diff (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1075657)
    at Object.diffLines (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1078582)
    at transact (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:487130)
    at TextBuffer.transact (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:491885)
    at TextBuffer.setTextViaDiff (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:487086)
    at CommitController.componentDidUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:4185601)
    at Xh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2441204)
    at Rh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2437643)
    at Uh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2437101)
    at Sh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2436927)
    at wh (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2436300)
    at kg (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2435547)
    at Object.enqueueSetState (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2411138)
    at ObserveModel.F.setState (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2337007)
    at ObserveModel.didUpdate (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:3375705)
    at ModelObserver._refreshModelData (C:\Users\<user>\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:3750538)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
l.tokenize	@	VM22 <embedded>:14
diff	@	VM22 <embedded>:14
diffLines	@	VM22 <embedded>:14
transact	@	VM22 <embedded>:11
transact	@	VM22 <embedded>:11
setTextViaDiff	@	VM22 <embedded>:11
componentDidUpdate	@	VM22 <embedded>:14
Xh	@	VM22 <embedded>:14
Rh	@	VM22 <embedded>:14
Uh	@	VM22 <embedded>:14
Sh	@	VM22 <embedded>:14
wh	@	VM22 <embedded>:14
kg	@	VM22 <embedded>:14
enqueueSetState	@	VM22 <embedded>:14
F.setState	@	VM22 <embedded>:14
didUpdate	@	VM22 <embedded>:14
_refreshModelData	@	VM22 <embedded>:14
_tickCallback	@	internal/process/next_tick.js:188
async function (async)		
_refreshModelData	@	VM22 <embedded>:14
refreshModelData	@	VM22 <embedded>:14
_refreshModelData	@	VM22 <embedded>:14
_tickCallback	@	internal/process/next_tick.js:188
async function (async)		
_refreshModelData	@	VM22 <embedded>:14
refreshModelData	@	VM22 <embedded>:14
e.activeModel.activeModelUpdateSubscription.e.onDidUpdate	@	VM22 <embedded>:14
simpleDispatch	@	VM22 <embedded>:11
emit	@	VM22 <embedded>:11
didUpdate	@	VM22 <embedded>:14
invalidateCacheAfterFilesystemChange	@	VM22 <embedded>:14
observeFilesystemChange	@	VM22 <embedded>:14
Repository.(anonymous function)	@	VM22 <embedded>:14
WorkdirContext.subs.add.observer.onDidChange.e	@	VM22 <embedded>:14
simpleDispatch	@	VM22 <embedded>:11
emit	@	VM22 <embedded>:11
didChange	@	VM22 <embedded>:14
currentFileWatcher.t	@	VM22 <embedded>:14
onNativeEvents	@	VM22 <embedded>:14
t.native.onDidChange.t	@	VM22 <embedded>:14
simpleDispatch	@	VM22 <embedded>:11
emit	@	VM22 <embedded>:11
onEvents	@	VM22 <embedded>:14
watcher.e	@	VM22 <embedded>:14
```
</p>
</details>

**Comment by JSn1nj4** [comment]
Oh, also, I opened a terminal and did `atom filename`. It opened the file in the current Atom window, and the GitHub package seemed to restart itself this time.
