### ISSUE TITLE
Atom/apm broken on Arch Linux

### ISSUE THREAD

**Issue by mon0theist** [atom/github#2032]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

apm is broken currently on Arch Linux, seemingly something to do with NodeJS but idk.

https://bbs.archlinux.org/viewtopic.php?id=219053

### Steps to Reproduce

1. Open Atom
2. Attempt to check for package updates
3. Get error message

OR

1. run apm version in terminal
2. Get error message

**Expected behavior:**

To be able to check for package updates and install new packages

**Actual behavior:**

Fetching outdated packages and themes failed.Hide output…
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal24NeverReadOnlySpaceObjectEPNS1_6ObjectE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Fetching outdated packages and themes failed.Hide output…
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal24NeverReadOnlySpaceObjectEPNS1_6ObjectE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

**Reproduces how often:**

Every time

### Versions

atom --version

atom --version
Atom    : 1.35.1
Electron: 3.1.6
Chrome  : 66.0.3359.181
Node    : 10.2.0

npm --version 
6.9.0

apm --version
apm --version
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal24NeverReadOnlySpaceObjectEPNS1_6ObjectE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

OS:
Arch Linux - GNOME 3.32

### Additional Information

Apparently it has something to do with nodejs but I'm not a developer so I have no idea. Atom was working fine until about a month or two ago.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

> Atom : 1.35.1
> Electron: 3.1.6

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by jmkeol** [comment]
I had this issue today and resolved it. To help anyone who is having this issue:

>It has been reported by some users that having an LTS version of node.js can break the package manager, some packages request an LTS version of nodejs so it is possible for a user to inadvertently change versions.<br>
>This can be rectified by installing nodejs, which should detect the conflict between the stable and LTS versions and then remove the LTS version.<br>
>[source](https://wiki.archlinux.org/index.php/Atom_(text_editor)#Package_Manager_not_working)

Just install the stable nodejs package:
```pacman -Syu nodejs```
