### ISSUE TITLE
Failed to initialize the github package

### ISSUE THREAD

**Issue by anandaltekar** [atom/github#2244]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [github](https://github.com/atom/github) package 0.29.0

### Stack Trace

Failed to initialize the github package

```
At Cannot call function 'isVisible' on missing remote object 1
Error: Cannot call function 'isVisible' on missing remote object 1
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)


Error: Cannot call function 'isVisible' on missing remote object 1
Error: Cannot call function 'isVisible' on missing remote object 1
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at new GitShellOutStrategy (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2399620)
    at e.map.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2302890)
    at Array.map (<anonymous>)
    at createForStrategies (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2302883)
    at Object.create (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2302295)
    at new Repository (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:620549)
    at Function.absentGuess (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:621042)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:614208)
    at new WorkdirContext (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:613297)
    at Function.guess (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:614097)
    at new GithubPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:819087)
    at Proxy.initialize (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:189687)
    at mainInitialized.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3420521)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418626)
    at Package.initializeIfNeeded (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3420382)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3421438)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3421016)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418626)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3420876)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3420819)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381612)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381228)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:331162)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381178)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:380728)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
file-icons 2.1.33 
Hydrogen 2.10.3 
project-manager 3.3.7 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by DomiiBunn** [comment]
OS: Ubuntu 18.04
Rest as above. 
The issue just happens when opening atom. It doesn't appear to break anything.
Non-Core Packages
```
gitlab 0.13-7
pigments 0.40.02
vue-fmt 0.1.1
ftp-remote-edit 0.17.2
```

**Comment by softwarecreations** [comment]
Also experienced this issue now.
Maybe it's some sort of race condition because I launched Atom without issue and then launched another instance and then this issue occurred.
I'm running Atom 1.40.1 x64 On Debian 10 Kernel 5.0.21
