### ISSUE TITLE
Npm run test broken on Windows with Atom Nightly

### ISSUE THREAD

**Issue by wadethestealth** [atom/github#2309]
Unable to run `npm run test` when only Atom Nightly is installed on Windows using local repository clone.

```bash
C:\Users\koids\Documents\GitHub\github-dev> npm run test

> github@0.31.0 test C:\Users\koids\Documents\GitHub\github-dev
> cross-env-shell NODE_ENV=development "${ATOM_SCRIPT_PATH:-atom} --test test"

The filename, directory name, or volume label syntax is incorrect.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn ${ATOM_SCRIPT_PATH:-atom} --test test ENOENT
    at notFoundError (C:\Users\koids\Documents\GitHub\github-dev\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\koids\Documents\GitHub\github-dev\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\koids\Documents\GitHub\github-dev\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\Users\koids\Documents\GitHub\github-dev\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github@0.31.0 test: `cross-env-shell NODE_ENV=development "${ATOM_SCRIPT_PATH:-atom} --test test"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github@0.31.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\koids\AppData\Roaming\npm-cache\_logs\2019-10-16T07_36_20_741Z-debug.log
```

**Comment by smashwilson** [comment]
👍 Yeah, I've noticed this too. `cross-env-shell` doesn't work like I thought it did 😅 We'll have to re-work that npm task.
