### ISSUE TITLE
Startup & Hydrogen issues

### ISSUE THREAD

**Issue by abekipnis** [atom/github#2773]
### Description
There was a Microsoft update on this computer I'm using, and after the update, Atom does not work with Hydrogen. I've tried uninstalling and installing Atom but it did not help. Starting up Atom, I get the following errors in the Developer Tools console:

**Actual behavior:**
```
electron/js2c/renderer_init.js:15 (electron) crashReporter.start is deprecated in the renderer process. Call it from the main process instead.
log @ electron/js2c/renderer_init.js:15
<embedded>:14 Uncaught (in promise) Error: Path must be a valid path to a file or a directory.
    at C:\Users\kipnisa1\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:14:1205414
    at NSFWNativeWatcher.doStart (C:\Users\kipnisa1\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:14:24657)
    at NSFWNativeWatcher.start (C:\Users\kipnisa1\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:14:22074)
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/kipnisa1/AppData/Local/atom/app-1.60.0/resources/app.asar/static/focus-trap.js.map: 
```
When I try to start a kernel \ run a cell in Hydrogen, I get the following error message:

> Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 22, in from IPython.core.application import ( File "C:\ProgramData\Anaconda3\lib\site-packages\IPython__init__.py", line 52, in from .terminal.embed import embed File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 15, in from IPython.core.interactiveshell import DummyMod, InteractiveShell File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 73, in from IPython.core.history import HistoryManager File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py", line 11, in import sqlite3 File "C:\ProgramData\Anaconda3\lib\sqlite3__init__.py", line 57, in from sqlite3.dbapi2 import * File "C:\ProgramData\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in
**Reproduces how often:**

### Versions

Atom    : 1.60.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1 x64

apm  2.6.2
npm  6.14.13
python 3.9.12
git 2.29.2.windows.2
visual studio

**Comment by abekipnis** [comment]
update: 

If I launch atom within an Anaconda prompt, then the Hydrogen Python 3 kernel works (this is a fine workaround for now) - but if I launch Hydrogen from the start window in Windows, then I get the same error as above. 

After the Windows updates occurred, I had to reinstall Python and all the packages, etc.

What is the fix for this?

**Comment by abekipnis** [comment]
If I run `python.exe -m ipykernel install --name "python_for_the_win"` in the Anaconda prompt, then Atom gives me the option for either Python 3 (ipykernel) or python_for_the_win when I try to start a kernel in Atom, but the error message is different depending on which one I select. 

If I choose python_for_the_win I get:

> Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main

whereas if I choose Python 3 I get:

> Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code

**Comment by xlr101** [comment]
Use Python scripts with pycharm integrated debugger ..... problem solved !
