### ISSUE TITLE
Unable to update to 6437caa3 in Atom

### ISSUE THREAD

**Issue by willf** [atom/github#450]
```
> nsfw@1.0.14 install /private/var/folders/6n/f05l2x_n1zgd75th4922yqhr0000gn/T/atom-git-package-clone-117018-31173-e1ksse/node_modules/nsfw
> node-gyp rebuild

  CC(target) Release/obj.target/openpa/openpa/src/opa_primitives.o
  CC(target) Release/obj.target/openpa/openpa/src/opa_queue.o
  LIBTOOL-STATIC Release/openpa.a
github@0.0.0 /private/var/folders/6n/f05l2x_n1zgd75th4922yqhr0000gn/T/atom-git-package-clone-117018-31173-e1ksse
├── atom-babel6-transpiler@0.0.3 
├─┬ babel-core@6.21.0 
│ ├─┬ babel-code-frame@6.20.0 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├── esutils@2.0.2 
│ │ └── js-tokens@2.0.0 
│ ├── babel-helpers@6.16.0 
│ ├── babel-messages@6.8.0 
│ ├─┬ babel-register@6.18.0 
│ │ ├── core-js@2.4.1 
│ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ └── os-homedir@1.0.2 
│ │ └── source-map-support@0.4.10 
│ ├─┬ babel-runtime@6.20.0 
│ │ └── regenerator-runtime@0.10.1 
│ ├── babel-template@6.16.0 
│ ├─┬ babel-traverse@6.21.0 
│ │ ├── globals@9.14.0 
│ │ └── invariant@2.2.2 
│ ├─┬ babel-types@6.21.0 
│ │ └── to-fast-properties@1.0.2 
│ ├── babylon@6.15.0 
│ ├── convert-source-map@1.3.0 
│ ├─┬ debug@2.6.0 
│ │ └── ms@0.7.2 
│ ├── json5@0.5.1 
│ ├── lodash@4.17.4 
│ ├─┬ minimatch@3.0.3 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├── path-is-absolute@1.0.1 
│ ├── private@0.1.6 
│ ├── slash@1.0.0 
│ └── source-map@0.5.6 
├─┬ babel-generator@6.21.0 
│ ├─┬ detect-indent@4.0.0 
│ │ └─┬ repeating@2.0.1 
│ │   └─┬ is-finite@1.0.2 
│ │     └── number-is-nan@1.0.1 
│ └── jsesc@1.3.0 
├─┬ babel-plugin-transform-async-to-generator@6.16.0 
│ ├── babel-helper-remap-async-to-generator@6.20.3 
│ └── babel-plugin-syntax-async-functions@6.13.0 
├─┬ babel-plugin-transform-class-properties@6.19.0 
│ ├── babel-helper-function-name@6.18.0 
│ └── babel-plugin-syntax-class-properties@6.13.0 
├─┬ babel-plugin-transform-decorators-legacy@1.3.4 
│ └── babel-plugin-syntax-decorators@6.13.0 
├── babel-plugin-transform-es2015-destructuring@6.19.0 
├─┬ babel-plugin-transform-es2015-modules-commonjs@6.18.0 
│ └── babel-plugin-transform-strict-mode@6.18.0 
├─┬ babel-plugin-transform-es2015-parameters@6.21.0 
│ ├─┬ babel-helper-call-delegate@6.18.0 
│ │ └── babel-helper-hoist-variables@6.18.0 
│ └── babel-helper-get-function-arity@6.18.0 
├─┬ babel-plugin-transform-object-rest-spread@6.20.2 
│ └── babel-plugin-syntax-object-rest-spread@6.13.0 
├─┬ babel-preset-react@6.16.0 
│ ├── babel-plugin-syntax-flow@6.18.0 
│ ├── babel-plugin-syntax-jsx@6.18.0 
│ ├── babel-plugin-transform-flow-strip-types@6.21.0 
│ ├── babel-plugin-transform-react-display-name@6.8.0 
│ ├─┬ babel-plugin-transform-react-jsx@6.8.0 
│ │ └── babel-helper-builder-react-jsx@6.21.1 
│ ├── babel-plugin-transform-react-jsx-self@6.11.0 
│ └── babel-plugin-transform-react-jsx-source@6.9.0 
├── classnames@2.2.5 
├── compare-sets@1.0.1 
├── core-decorators@0.15.0 
├── diff@2.2.2 
├─┬ etch@0.8.0 
│ └─┬ virtual-dom@2.1.1 
│   ├── browser-split@0.0.1 
│   ├─┬ error@4.4.0 
│   │ ├── camelize@1.0.0 
│   │ ├── string-template@0.2.1 
│   │ └── xtend@4.0.1 
│   ├─┬ ev-store@7.0.0 
│   │ └── individual@3.0.0 
│   ├─┬ global@4.3.1 
│   │ ├─┬ min-document@2.19.0 
│   │ │ └── dom-walk@0.1.1 
│   │ └── process@0.5.2 
│   ├── is-object@1.0.1 
│   ├── next-tick@0.2.2 
│   ├── x-is-array@0.1.0 
│   └── x-is-string@0.1.0 
├─┬ git-kitchen-sink@1.17.0 
│ ├─┬ checksum@0.1.1 
│ │ └─┬ optimist@0.3.7 
│ │   └── wordwrap@0.0.3 
│ ├─┬ decompress@4.0.0 
│ │ ├─┬ decompress-tar@4.1.0 
│ │ │ ├── file-type@3.9.0 
│ │ │ ├── is-stream@1.1.0 
│ │ │ └─┬ tar-stream@1.5.2 
│ │ │   ├── bl@1.2.0 
│ │ │   ├── end-of-stream@1.1.0 
│ │ │   └─┬ readable-stream@2.2.2 
│ │ │     ├── buffer-shims@1.0.0 
│ │ │     ├── core-util-is@1.0.2 
│ │ │     ├── isarray@1.0.0 
│ │ │     ├── process-nextick-args@1.0.7 
│ │ │     ├── string_decoder@0.10.31 
│ │ │     └── util-deprecate@1.0.2 
│ │ ├─┬ decompress-tarbz2@4.1.0 
│ │ │ ├─┬ seek-bzip@1.0.5 
│ │ │ │ └── commander@2.8.1 
│ │ │ └─┬ unbzip2-stream@1.0.10 
│ │ │   ├─┬ buffer@3.6.0 
│ │ │   │ ├── base64-js@0.0.8 
│ │ │   │ └── ieee754@1.1.8 
│ │ │   └── through@2.3.8 
│ │ ├── decompress-targz@4.0.0 
│ │ ├─┬ decompress-unzip@4.0.1 
│ │ │ ├── get-stream@2.3.1 
│ │ │ └─┬ yauzl@2.7.0 
│ │ │   ├── buffer-crc32@0.2.13 
│ │ │   └─┬ fd-slicer@1.0.1 
│ │ │     └── pend@1.2.0 
│ │ ├── pify@2.3.0 
│ │ └─┬ strip-dirs@1.1.1 
│ │   ├── get-stdin@4.0.1 
│ │   ├─┬ is-absolute@0.1.7 
│ │   │ └── is-relative@0.1.3 
│ │   ├── is-natural-number@2.1.1 
│ │   ├── minimist@1.2.0 
│ │   └── sum-up@1.0.3 
│ ├── gzip@0.1.0 
│ ├── os-tmpdir@1.0.2 
│ ├── progress@1.1.8 
│ ├─┬ request@2.79.0 
│ │ ├── aws-sign2@0.6.0 
│ │ ├── aws4@1.5.0 
│ │ ├── caseless@0.11.0 
│ │ ├─┬ combined-stream@1.0.5 
│ │ │ └── delayed-stream@1.0.0 
│ │ ├── extend@3.0.0 
│ │ ├── forever-agent@0.6.1 
│ │ ├─┬ form-data@2.1.2 
│ │ │ └── asynckit@0.4.0 
│ │ ├─┬ har-validator@2.0.6 
│ │ │ ├─┬ commander@2.9.0 
│ │ │ │ └── graceful-readlink@1.0.1 
│ │ │ ├─┬ is-my-json-valid@2.15.0 
│ │ │ │ ├── generate-function@2.0.0 
│ │ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ │ └── is-property@1.0.2 
│ │ │ │ └── jsonpointer@4.0.1 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ hawk@3.1.3 
│ │ │ ├── boom@2.10.1 
│ │ │ ├── cryptiles@2.0.5 
│ │ │ ├── hoek@2.16.3 
│ │ │ └── sntp@1.0.9 
│ │ ├─┬ http-signature@1.1.1 
│ │ │ ├── assert-plus@0.2.0 
│ │ │ ├─┬ jsprim@1.3.1 
│ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ └── verror@1.3.6 
│ │ │ └─┬ sshpk@1.10.2 
│ │ │   ├── asn1@0.2.3 
│ │ │   ├── assert-plus@1.0.0 
│ │ │   ├── bcrypt-pbkdf@1.0.0 
│ │ │   ├─┬ dashdash@1.14.1 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── ecc-jsbn@0.1.1 
│ │ │   ├─┬ getpass@0.1.6 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── jodid25519@1.0.2 
│ │ │   ├── jsbn@0.1.0 
│ │ │   └── tweetnacl@0.14.5 
│ │ ├── is-typedarray@1.0.0 
│ │ ├── isstream@0.1.2 
│ │ ├── json-stringify-safe@5.0.1 
│ │ ├─┬ mime-types@2.1.14 
│ │ │ └── mime-db@1.26.0 
│ │ ├── oauth-sign@0.8.2 
│ │ ├── qs@6.3.0 
│ │ ├── stringstream@0.0.5 
│ │ ├─┬ tough-cookie@2.3.2 
│ │ │ └── punycode@1.4.1 
│ │ ├── tunnel-agent@0.4.3 

│ │ └── uuid@3.0.1 
│ ├─┬ rimraf@2.5.4 
│ │ └─┬ glob@7.1.1 
│ │   ├── fs.realpath@1.0.0 
│ │   ├─┬ inflight@1.0.6 
│ │   │ └── wrappy@1.0.2 
│ │   └── once@1.3.3 
│ └─┬ tar@2.2.1 
│   ├── block-stream@0.0.9 
│   ├─┬ fstream@1.0.10 
│   │ └── graceful-fs@4.1.11 
│   └── inherits@2.0.3 
├─┬ mkdirp@0.5.1 
│ └── minimist@0.0.8 
├── multi-list-selection@0.1.1 
├── ncp@2.0.0 
├─┬ react@15.4.2 
│ ├─┬ fbjs@0.8.8 
│ │ ├── core-js@1.2.7 
│ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ ├─┬ node-fetch@1.6.3 
│ │ │ │ └─┬ encoding@0.1.12 
│ │ │ │   └── iconv-lite@0.4.15 
│ │ │ └── whatwg-fetch@2.0.1 
│ │ ├─┬ promise@7.1.1 
│ │ │ └── asap@2.0.5 
│ │ ├── setimmediate@1.0.5 
│ │ └── ua-parser-js@0.7.12 
│ ├─┬ loose-envify@1.3.1 
│ │ └── js-tokens@3.0.0 
│ └── object-assign@4.1.1 
├── react-dom@15.4.2 
├─┬ recursive-readdir@2.1.0 
│ └── minimatch@3.0.2 
├── semver@5.3.0 
├─┬ temp@0.8.3 
│ └── rimraf@2.2.8 
├── tree-kill@1.1.0 
└── what-the-diff@0.3.0 


Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/openpa.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/6n/f05l2x_n1zgd75th4922yqhr0000gn/T/atom-git-package-clone-117018-31173-e1ksse/node_modules/nsfw
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 16.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/willf/.atom/.apm/.apmrc" "--userconfig" "/Users/willf/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.13" "--arch=x64"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! nsfw@1.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nsfw@1.0.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nsfw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nsfw
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nsfw
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/6n/f05l2x_n1zgd75th4922yqhr0000gn/T/atom-git-package-clone-117018-31173-e1ksse/npm-debug.log
```
### Versions

Atom Version (`atom --version`):

Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

GitHub Package Version (`git --git-dir ~/.atom/packages/github/.git rev-parse head`):

bea2da8b554d8528dae3065a2917aec8aab05570

**Comment by kuychaco** [comment]
No longer relevant since we're bundling the package in core now :)
