### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by rashanjibowu** [atom/github#794]
[Enter steps to reproduce:]

1. Open Atom
2. Open some project or folder
3. Make a change to code (JS or HTML)

**Atom**: 1.18.0-dev-1992c17 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [github](https://github.com/atom/github) package 0.0.6

### Stack Trace

Uncaught TypeError: Cannot read property 'map' of undefined

```
At /usr/local/share/atom/resources/app/node_modules/github/lib/models/workdir-context.js:148

TypeError: Cannot read property 'map' of undefined
    at WorkdirContext.subs.add.observer.onDidChange.events (/usr/local/share/atom/resources/app/node_modules/github/lib/models/workdir-context.js:148:1)
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at WorkspaceChangeObserver.didChange (/usr/local/share/atom/resources/app/node_modules/github/lib/models/workspace-change-observer.js:138:1)
    at focusHandler (/usr/local/share/atom/resources/app/node_modules/github/lib/models/workspace-change-observer.js:108:1)
```

### Commands

```
     -0:49.3.0 application:open-folder (input.hidden-input)
  2x -0:33.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.8.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-clock 0.1.7 
```

**Comment by BinaryMuse** [comment]
@smashwilson It looks like the `WorkspaceChangeObserver` emits a `did-change` event with no arguments (so `events` is undefined in the `WorkdirContext` handler).

I could work around the error by adding an empty array to the event emission, but the `Preset` repo state only refreshes certain cache keys based on the paths, so it seems like it wouldn't do anything. Should this emission just be removed?

**Comment by BinaryMuse** [comment]
Ah it looks like this is the `focus` handler — since we get less fs events from the Linux observer, we always sort-of assumed that everything might have changed when the window was re-focused. This was very old code. @smashwilson, any thoughts on how to bring this up to date?

**Comment by smashwilson** [comment]
The `WorkspaceChangeObserver` uses a real filesystem watcher for the `.git` directory and the focus events as a stand-in for working directory changes, so maybe we could synthesize a working directory change so that similar cache keys are removed?
