### ISSUE TITLE
Uncaught TypeError: this.resolveReady is not a function

### ISSUE THREAD

**Issue by airhorns** [atom/github#815]
All I did was upgrade from 1.17.0 to 1.18.0-beta0 and restart my editor, I had one or two Ruby files open. Let me know what more context I can gather!

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [github](https://github.com/atom/github) package 0.0.9

### Stack Trace

Uncaught TypeError: this.resolveReady is not a function

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/github/lib/worker-manager.js:462

TypeError: this.resolveReady is not a function
  at emitter.on._ref10 (<embedded>:96333:18)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:62928:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63044:34)
  at EventEmitter.handleMessages (<embedded>:96323:28)
  at emitTwo (events.js:106:13)
  at EventEmitter.emit (events.js:191:7)

```

### Commands

```
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.24 
atom-ctags 5.0.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.3 
aurora-theme 1.2.2 
autocomplete-glsl 0.2.3 
autocomplete-python 1.8.63 
autocomplete-ruby 0.2.8 
autocomplete-webgl 1.1.0 
busy-signal 1.4.1 
clipboard-plus 0.5.1 
dash 1.7.1 
ex-mode 0.14.0 
expand-region 0.3.0 
formatter 2.12.4 
gloom 0.5.0 
intentions 1.1.2 
language-babel 2.61.0 
language-batch 0.4.0 
language-chef 0.9.0 
language-elm 1.5.0 
language-fish-shell 1.0.5 
language-glsl 2.0.1 
language-powershell 4.0.0 
language-rust 0.4.10 
language-scala 1.1.8 
language-terraform 0.8.1 
language-varnish 0.6.0 
line-length-break 0.4.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-flake8 2.2.1 
linter-glsl 2.1.3 
linter-pep8 1.3.2 
linter-pycodestyle 2.0.2 
linter-rubocop 2.1.1 
linter-rust 0.8.0 
linter-ui-default 1.3.0 
linter-write-good 0.9.0 
local-history 4.1.1 
merge-conflicts 1.4.5 
minimap-selection 4.4.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nuclide-flow 0.0.32 
nuclide-type-hint 0.0.32 
pigments 0.39.1 
revert-buffer 0.5.0 
ruby-test 1.0.2 
tabs-to-spaces 1.0.3 
vim-mode 0.66.0 
vim-surround 0.8.1 
wordcount 2.10.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a couple of things for us?

* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by airhorns** [comment]
> is the error is reproducible?
Yep, pops up each time I open the beta .app .

> if reproducible, do you see the error in safe mode (atom --safe)?

I do not see the error in safe mode, which makes sense right because because safe mode disables all packages?

**Comment by rsese** [comment]
> I do not see the error in safe mode, which makes sense right because because safe mode disables all packages?

lol sorry, didn't completely edit that canned reply, thanks for confirming you can reproduce :v:

**Comment by rsese** [comment]
@smashwilson do you think there anything y'all might want to look at while it's reproducible before we try something like clearing saved state?

**Comment by smashwilson** [comment]
@rsese Wait - safe mode doesn't disable _core_ packages, right? Otherwise things like tree-view wouldn't work in safe mode either.

**Comment by rsese** [comment]
Ohhh right, the GitHub package is a core package 😆 sorry @smashwilson.

@airhorns - since it's not reproducible in safe mode, then one of your community packages may be causing the error.  You can disable them all and then enable one-by-one to find the culprit or since you have quite a few installed packages, https://atom.io/packages/package-cop might be helpful too.

**Comment by micaelmbagira** [comment]
I have the same from today in 1.18.0

**Comment by rsese** [comment]
@micaelmbagira - do you have steps to reproduce that you can share?  And if reproducible, can you reproduce in safe mode (`atom --safe`)?

**Comment by tvalentius** [comment]
@rsese 

I am having the same issue after update to 1.18.0 today
and yes i can reproduce it even on safe mode

**Comment by micaelmbagira** [comment]
@rsese It pops up every time when I open the app, but in safe mode, **it works**, I don't have the error showing up.

**Comment by rsese** [comment]
> I am having the same issue after update to 1.18.0 today
> and yes i can reproduce it even on safe mode.

> It pops up each time i open the app.

Hmm, if you temporarily reset to factory defaults, do you still get the error @tvalentius?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

> It pops up every time when I open the app, but in safe mode, it works, I don't have the error showing up.
> It might be obvious, but when I disable the github package, i can't reproduce the error anymore.

@micaelmbagira if you don't see the error in safe mode, then it's likely that one of your community packages is causing the issue.  You can try disabling all your community packages and enabling them one-by-one to pinpoint the package.

**Comment by micaelmbagira** [comment]
@rsese Weird thing, since today the error doesn't show up... Maybe the incriminated package got updated

**Comment by masom** [comment]
I'm also able to reproduce this error. Disabling the github package stops it from happening.

**Comment by rsese** [comment]
> Weird thing, since today the error doesn't show up... Maybe the incriminated package got updated

Oh good to know, glad you're not seeing the error anymore @micaelmbagira :v:

@masom - if you enable the github package and then start in safe mode (`atom --safe`), do you still get the error?

**Comment by miamollie** [comment]
I had this error starting yesterday, similarly did not appear in `--safe` mode.

Updated all community packages and it went away.

```
├── MagicPython@1.0.10
├── atom-beautify@0.30.3
├── atom-html-preview@0.1.22
├── autoclose-html@0.23.0
├── file-icons@2.1.7
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.66.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-rust@0.4.10
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0
├── linter-eslint@8.2.1
├── merge-conflicts@1.4.5
├── nuclide@0.232.0
├── nuclide-format-js@0.0.36
├── prettier-atom@0.34.0
├── ruby-slim@0.2.0
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── svgo@2.8.5
└── tool-bar@1.1.0
```

Of those I have only the following in common with @airhorns, so maybe that helps narrow it down a wee bit. 

```
├── atom-beautify@0.30.3
├── language-babel@2.66.0
├── linter@2.2.0
├── linter-eslint@8.2.1
├── merge-conflicts@1.4.5
```

**Comment by urikphytech** [comment]
+1 happens to me on version 1.18.0

**Comment by Lukkub** [comment]
+1 happens to me on version 1.18.0

**Comment by BinaryMuse** [comment]
While I understand the frustration of software that's not behaving, "+1" comments aren't very helpful unless they provide a bit more information. In particular, @rsese's question [above](https://github.com/atom/github/issues/815#issuecomment-309527663) about whether or not this reproduces in safe mode is very helpful — if using safe mode makes the problem go away, then there's likely a problem with a community package that's conflicting in some way. If you find this is the case, and you're willing to share what packages you have installed, it might help us track down the issue a little faster. Thanks! :bowing_woman:

**Comment by masom** [comment]
`atom --safe` does not trigger the error.

`facebooknuclideapm/nuclide-flow` is the package producing the errors.

**Comment by knasim** [comment]
i'm experiencing the same - upon opening any *js file. 
version:  1.18.0

**Comment by knasim** [comment]
i do have facebooknuclideapm installed

**Comment by knasim** [comment]
Just update facebooknuclideapm plugin and this annoying popup modal shall go away. 
Originally pointed out by @masom
