### ISSUE TITLE
Improve handling of 2FA credentials

### ISSUE THREAD

**Issue by smashwilson** [atom/github#844]
When pushing, pulling, or fetching against an HTTPS remote for a private repository while you have 2fa enabled, you need to provide [a personal access token](https://help.github.com/articles/providing-your-2fa-authentication-code/#when-youll-be-asked-for-a-personal-access-token-as-a-password) instead of your password to authenticate. We could stand to make this smoother, or at least hint about this in the UI text.

**Comment by cameronmcefee** [comment]
Yes please! I ran into this today and only know how to log in thanks to your issue. Here's what I've experienced:

1. Did the initial "log into atom to get your token" rigamarole. Assumed I was good to go.
1. Tried to pull, asked to log in.
1. Tried to log in with normal creds (as you mentioned). Failed.
1. Found this post, didn't know what permissions to give the token, guessed "repo" scope.
1. Logged in with username + token, modal dismissed, said I didn't have permission. However the progress indicator stayed up and the pull icon was a sync icon for a bit.
1. Tried to pull again, was prompted to log in again.

**Comment by adrian3H** [comment]
There are deeper issues with push and pull when using the Github package in Atom on a Mac. I created a personal access token.  And I entered that the next time I got the login overlay. But it didn't work. Each time I push, I get the log-in overlay. And I usually have to enter my username and password (or keychain) three times before the push works.

I tried changing the password in the atom-github keychain in keychain access, to my new personal access token. Still no luck.

Interesting - the GitHub desktop app accesses a different Keychain. It picked up the (pre-existing?) GitHub for Mac SSH keychain. That keychain is similar to another keychain called github.com/mac. Note - I have no problem pushing and pulling via the GitHub desktop app on Mac. Perhaps the GitHub package for Atom needs to add itself to that existing Keychain rather than creating its own Keychain. In other words, it needs to adopt the same authorisation method as the GitHub desktop app.

**Comment by smashwilson** [comment]
@cameronmcefee: "Repo" scope should be what you need for your token. Can you pull from the command-line with the same username and token?

@adrian3H: I agree, it's a little clunky right now.

> And I usually have to enter my username and password (or keychain) three times before the push works.

This is odd. Are the first two pushes timing out or something? Do you get any other feedback in the git output from the error message?

> Perhaps the GitHub package for Atom needs to add itself to that existing Keychain rather than creating its own Keychain. In other words, it needs to adopt the same authorisation method as the GitHub desktop app.

Right now the keychain is manipulated with the command-line `git-credential-osxkeychain` helper. No reason we couldn't make sure that we re-use the same keychain credentials when we tackle #861, though.

_For both of you:_ you can get more detailed diagnostic output for git commands by opening your dev console and running:

```
atom.config.set('github.gitDiagnostics', true)
```

That will cause git operations to run with `GIT_TRACE=1` and dump the full stdout and stderr of each command to the dev console. That might be helpful to track down why your pushes are intermittently failing?

**Comment by adrian3H** [comment]
Thanks for your quick response. 

Ok, I enabled git diagnostics and opened dev tools within Atom, did a push and then expanded Git:git-c. 

This is weird. Once again I had to enter my username and password 3 times before the push worked. But the first two times I submitted, I didn't see an error in the console.

Here's the log inside Git:git-c 

git:git -c gpg.program=/Applications/Atom.app/Contents/Resources/app/node_modules/github/bin/gpg-no-tty.sh commit -m stage 2 - flex layout with space-around distribution on vertical axis in [path removed - my redaction - adrian3H] 
<embedded>:175976 exit status 0
<embedded>:175977 stdout
<embedded>:175978 [RSVP-7655 7edf1f4a0d] stage 2 - flex layout with space-around distribution on vertical axis
 2 files changed, 47 insertions(+), 38 deletions(-)

<embedded>:175979 stderr
<embedded>:175980 09:53:03.663035 git.c:369               trace: built-in: git 'commit' '-m' 'stage 2 - flex layout with space-around distribution on vertical axis'

Wait! I found this inside git:git push:

stderr
<embedded>:175980 09:53:15.416766 git.c:369               trace: built-in: git 'push' 'origin' 'RSVP-7655'
09:53:15.522845 run-command.c:369       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/3HGroup/rsvp.git'
09:53:15.562966 http.c:638              == Info: Couldn't find host github.com in the .netrc file; using defaults
09:53:15.574536 http.c:638              == Info:   Trying 192.30.255.113...
09:53:15.574575 http.c:638              == Info: TCP_NODELAY set
09:53:15.772259 http.c:638              == Info: Connected to github.com (192.30.255.113) port 443 (#0)
09:53:16.259106 http.c:638              == Info: TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
09:53:16.259350 http.c:638              == Info: Server certificate: github.com
09:53:16.259487 http.c:638              == Info: Server certificate: DigiCert SHA2 Extended Validation Server CA
09:53:16.259563 http.c:638              == Info: Server certificate: DigiCert High Assurance EV Root CA
09:53:16.260066 http.c:585              => Send header, 0000000165 bytes (0x000000a5)
09:53:16.260085 http.c:597              => Send header: GET /3HGroup/rsvp.git/info/refs?service=git-receive-pack HTTP/1.1
09:53:16.260092 http.c:597              => Send header: Host: github.com
09:53:16.260098 http.c:597              => Send header: User-Agent: git/2.13.0
09:53:16.260104 http.c:597              => Send header: Accept: */*
09:53:16.260109 http.c:597              => Send header: Accept-Encoding: gzip
09:53:16.260114 http.c:597              => Send header: Pragma: no-cache
09:53:16.260119 http.c:597              => Send header:
09:53:16.461593 http.c:585              <= Recv header, 0000000037 bytes (0x00000025)
09:53:16.461626 http.c:597              <= Recv header: HTTP/1.1 401 Authorization Required
09:53:16.461638 http.c:585              <= Recv header, 0000000026 bytes (0x0000001a)
09:53:16.461645 http.c:597              <= Recv header: Server: GitHub Babel 2.0
09:53:16.461653 http.c:585              <= Recv header, 0000000026 bytes (0x0000001a)
09:53:16.461659 http.c:597              <= Recv header: Content-Type: text/plain
09:53:16.461691 http.c:585              <= Recv header, 0000000020 bytes (0x00000014)
09:53:16.461701 http.c:597              <= Recv header: Content-Length: 21
09:53:16.461711 http.c:585              <= Recv header, 0000000040 bytes (0x00000028)
09:53:16.461719 http.c:597              <= Recv header: WWW-Authenticate: Basic realm="GitHub"
09:53:16.461727 http.c:585              <= Recv header, 0000000058 bytes (0x0000003a)
09:53:16.461733 http.c:597              <= Recv header: X-GitHub-Request-Id: E822:1DF46:11E085F:1B1B3EC:594B06EB
09:53:16.461741 http.c:585              <= Recv header, 0000000023 bytes (0x00000017)
09:53:16.461747 http.c:597              <= Recv header: X-Frame-Options: DENY
09:53:16.461754 http.c:585              <= Recv header, 0000000002 bytes (0x00000002)
09:53:16.461760 http.c:597              <= Recv header:
09:53:16.461767 http.c:611              <= Recv data, 0000000021 bytes (0x00000015)
09:53:16.461772 http.c:626              <= Recv data: Repository not found.
09:53:16.461786 http.c:638              == Info: Curl_http_done: called premature == 0
09:53:16.461828 http.c:638              == Info: Connection #0 to host github.com left intact
09:53:16.462774 run-command.c:369       trace: run_command: '/private/var/folders/rk/hhdyftqj6r5194ddw_hb8k2c0000gp/T/github-117522-20192-10snooi.s3muqh0k9/git-credential-atom.sh get'
09:53:16.466987 run-command.c:228       trace: exec: '/bin/sh' '-c' '/private/var/folders/rk/hhdyftqj6r5194ddw_hb8k2c0000gp/T/github-117522-20192-10snooi.s3muqh0k9/git-credential-atom.sh get' '/private/var/folders/rk/hhdyftqj6r5194ddw_hb8k2c0000gp/T/github-117522-20192-10snooi.s3muqh0k9/git-credential-atom.sh get'
git-credential-atom: working directory = /Users/adrian.hall/source/rsvp
git-credential-atom: socket path = /private/var/folders/rk/hhdyftqj6r5194ddw_hb8k2c0000gp/T/github-117522-20192-10snooi.s3muqh0k9/helper.sock
git-credential-atom: action = get
git-credential-atom: parsed from stdin: [protocol] = [https]
git-credential-atom: parsed from stdin: [host] = [github.com]
git-credential-atom: all input received: EOF from stdin
git-credential-atom: discover credential helpers from system git configuration
git-credential-atom: PATH = /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
git-credential-atom: failed to list credential helpers. this is ok
Error: Command failed: git config --system --get-all credential.helper

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
git-credential-atom: attempting to run fill with user-configured credential helpers
git-credential-atom: GIT_ASKPASS = 
git-credential-atom: SSH_ASKPASS = 
git-credential-atom: arguments = credential fill
git-credential-atom: stdin =
protocol=https
host=github.com


git-credential-atom: stdout:

git-credential-atom: stderr:
09:53:16.772291 git.c:369               trace: built-in: git 'credential' 'fill'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

git-credential-atom: user-configured credential helpers failed with exit code 128. this is ok
git-credential-atom: requesting dialog through Atom socket
git-credential-atom: prompt = "Please enter your credentials for https://github.com" includeUsername = true
git-credential-atom: connection established
git-credential-atom: writing payload
git-credential-atom: payload written
git-credential-atom: Atom socket stream terminated
git-credential-atom: Atom reply parsed
git-credential-atom: success

........ [lot's more 'cause I tried three times] ....

Error: Command failed: git config --system --get-all credential.helper

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
git-credential-atom: attempting to run approve with user-configured credential helpers
git-credential-atom: GIT_ASKPASS = 
git-credential-atom: SSH_ASKPASS = 
git-credential-atom: arguments = credential approve
git-credential-atom: stdin =

**Comment by adrian3H** [comment]
NB - the account name I'm using is the account listed in the keychain 'GitHub for MacSSH key passphrase'. That account name is my own email address (provided by my company). The password I'm using is the password (appears to be a token - longand  alphanumeric) in that same keychain. However, the account listed in the 'atom-github' keychain is 'https://api.github.com' - i.e. NOT my own email address. That could be significant.

**Comment by adrian3H** [comment]
I resolved the issue by installing git via homebrew, then adding 
export PATH="/usr/local/bin:${PATH}"
to ~/.bash_profile
and then restarting.

**Comment by cameronmcefee** [comment]
@smashwilson In my case, I think it was a case of compounded lack of UI + user error. Just this week (about a month from the OP) I got a notification that one of the orgs I'm a member of approved Atom as a third-party GitHub application. It's been long enough that I forget which project I was trying to push to, but I'm willing to believe it was one for this org, since it's my day job. While I call this user error, it wasn't ever clear to me that Atom is a an app that needs org approval. It would have been great to get some sort of message that said "Hey, your org admin hasn't approved Atom yet".

**Comment by ipat8** [comment]
Just adding myself here to track when this is fixed.
