### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by alexanderepstein** [atom/github#881]
[Enter steps to reproduce:]

1. Deleted the root project folder off of my computer while it was still open in Atom

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: elementary OS
**Thrown From**: [github](https://github.com/atom/github) package 0.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/share/atom-beta/resources/app/node_modules/github/lib/worker-manager.js:322

TypeError: Cannot read property 'id' of undefined
    at Worker.handleSpawnError (/usr/share/atom-beta/resources/app/node_modules/github/lib/worker-manager.js:322:1)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at EventEmitter.handleMessages (/usr/share/atom-beta/resources/app/node_modules/github/lib/worker-manager.js:452:1)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
busy-signal 1.4.1 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-pylama 0.8.20 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.0 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
python-autopep8 0.1.3 
```

**Comment by BinaryMuse** [comment]
Saw this same error on github 0.3.0 (Atom 1.19.0-dev-7a93e9d8c). Couldn't reproduce it, so it seems to be sporadic.

I think this will be completely resolved when we move to Web Workers (since there's no need to identify the processes to send/receive messages to/from).
