### ISSUE TITLE
Unable to push

### ISSUE THREAD

**Issue by gcorboz** [atom/github#902]
### Description

Instead of GITHUB I'm using Enterprise GITHUB and when I try and push commits I get an "Unable to push" error.

The detailed error message is as below but I've masked our enterprise URL:
fatal: unable to access 'https://aaa/bbb/ccc.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

### Steps to Reproduce

1. Push

**Expected behavior:**

I expected my commits to be pushed to the Enterprise GITHUB

**Actual behavior:**

Received an Unable to Push error.

### Versions
Atom Beta
1.18.0-beta2 x64

**Comment by TheSpeedyBlur** [comment]
To extend on this issue, the problem is that the username is not preserved, because it is already in the git URL. The authentication fails because of that.

Example debug log:

```
git-credential-atom: working directory = /var/www/html/phplib
git-credential-atom: socket path = /tmp/github-11755-17965-wizo5v.pzlrllerk9/helper.sock
git-credential-atom: action = get
git-credential-atom: parsed from stdin: [protocol] = [https]
git-credential-atom: parsed from stdin: [host] = [<gitlab url>]
git-credential-atom: parsed from stdin: [username] = [forcemagic]
git-credential-atom: all input received: EOF from stdin
git-credential-atom: discover credential helpers from system git configuration
git-credential-atom: PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
git-credential-atom: failed to list credential helpers. this is ok
Error: Command failed: git config --system --get-all credential.helper

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket. (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
git-credential-atom: attempting to run fill with user-configured credential helpers
git-credential-atom: GIT_ASKPASS = 
git-credential-atom: SSH_ASKPASS = 
git-credential-atom: arguments = credential fill
git-credential-atom: stdin =
protocol=https
host=<gitlab url>
username=forcemagic


git-credential-atom: stdout:

git-credential-atom: stderr:
08:09:21.144397 git.c:371               trace: built-in: git 'credential' 'fill'
fatal: could not read Password for 'https://forcemagic@<gitlab url>': terminal prompts disabled

git-credential-atom: user-configured credential helpers failed with exit code 128. this is ok
git-credential-atom: requesting dialog through Atom socket
git-credential-atom: prompt = "Please enter your credentials for https://forcemagic@<gitlab url>"
                     includeUsername = false
git-credential-atom: connection established
git-credential-atom: writing payload
git-credential-atom: payload written
git-credential-atom: Atom socket stream terminated
git-credential-atom: Atom reply parsed
git-credential-atom: success
08:10:31.894263 run-command.c:369       trace: run_command: '/tmp/github-11755-17965-wizo5v.pzlrllerk9/git-credential-atom.sh erase'
08:10:31.894835 run-command.c:228       trace: exec: '/bin/sh' '-c' '/tmp/github-11755-17965-wizo5v.pzlrllerk9/git-credential-atom.sh erase' '/tmp/github-11755-17965-wizo5v.pzlrllerk9/git-credential-atom.sh erase'
git-credential-atom: working directory = /var/www/html/phplib
git-credential-atom: socket path = /tmp/github-11755-17965-wizo5v.pzlrllerk9/helper.sock
git-credential-atom: action = erase
git-credential-atom: parsed from stdin: [protocol] = [https]
git-credential-atom: parsed from stdin: [host] = [<gitlab url>]
git-credential-atom: parsed from stdin: [username] = []
git-credential-atom: parsed from stdin: [password] = [******]
git-credential-atom: all input received: EOF from stdin
git-credential-atom: discover credential helpers from system git configuration
git-credential-atom: PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
git-credential-atom: failed to list credential helpers. this is ok
Error: Command failed: git config --system --get-all credential.helper

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket. (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
git-credential-atom: attempting to run reject with user-configured credential helpers
git-credential-atom: GIT_ASKPASS = 
git-credential-atom: SSH_ASKPASS = 
git-credential-atom: arguments = credential reject
git-credential-atom: stdin =
protocol=https
host=<gitlab url>
username=
password=*******


remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://forcemagic@<gitlab url>/forcemagic/phplib.git/'
```

**Comment by smashwilson** [comment]
> Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

* Are you able to push successfully on the command line?
* Are you behind a proxy of some kind? Did you need to do anything to configure git to push and pull through the proxy? We might not be propagating those settings properly.

**Comment by gcorboz** [comment]
Hi Smashwilson
I am able to push successfully to our enterprise GIT using other git tools/command line/etc.

I have to configure the proxy though to get through our firewall.

I'm not sure how to set the proxy settings within Atom though.

**Comment by gcorboz** [comment]
I'm closing this issue - There was an issue with a corporate certificate

**Comment by gcorboz** [comment]
I reopened this as while the certificate issue was resolved - Atom didn't handle that properly while other GIT applications did.

**Comment by adrian3H** [comment]
I am constantly prompted for username and password when pushing, using the Github package in Atom on a Mac. And I usually have to enter my username and password (or keychain) three times before the push works. After entering my username and password, the log-in overlay disappears, then reappears with empty fields after a few seconds. I have to reenter my username and password. This happens at least twice before the push finally goes through successfully.

NB - I have no problem pushing via the command line or via the GitHub Desktop app.

I tried safe mode and I tried clearing saved state. Neither worked. The result was the same as described above.

I also created a personal access token. And I entered that the next time I got the login overlay. But it didn't work. The result was the same as described above.

I thought the issue might be with the atom-github keychain. I changed the password in the atom-github keychain in keychain access, to my new personal access token. Still no luck.

It may be relevant that the GitHub desktop app and the GitHub package in Atom appear to access different keychains. The atom-github keychain has the account listed as https://api.github.com. The GitHub desktop app accesses the (pre-existing?) GitHub for Mac SSH keychain, which lists the account as my personal github account name (email address). (Note - that keychain is almost identical to another keychain called github.com/mac.) 

Perhaps the GitHub package for Atom needs to add itself to that existing GitHub for Mac SSH Keychain, rather than creating its own Keychain. In other words, it needs to adopt the same authorisation method as the GitHub desktop app.

**Comment by smashwilson** [comment]
@gcorboz: Ah, got it. I'm guessing that we aren't propagating the git settings related to your proxy to the git subprocess properly.

If you don't mind my asking, how do you configure git to use your proxy ordinarily? Do you set environment variables, git config settings, or does it pick up your OS network settings? Also, what OS are you on?

**Comment by gcorboz** [comment]
I'm using Windows 7 Enterprise. 
To configure proxy and certificate settings I used git config in the command line. GIT for windows comes with a bash terminal.

**Comment by thtliife** [comment]
> @gcorboz: Ah, got it. I'm guessing that we aren't propagating the git settings related to your proxy to the git subprocess properly.

I think this may be the case... 
I have my proxy set via apmrc, environment variables and .gitconfig
Atom gets out through the proxy no problems for package installation.
I can use git without issue in terminal.
However, the atom github package refuses to get out through the proxy.

I also notice this in the devtools console on every save of a file in a git repo:
`fetchWithRetries.js:52 POST https://api.github.com/graphql net::ERR_TUNNEL_CONNECTION_FAILED`

This error goes away when I disable the github package

**Comment by angrydonald** [comment]
I have the same problem on windows : 
schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) The revocation function was unable to check revocation because the revocation server was offline

Push and pull ko. A proxy is in .atom/.apmrc and it works (updates ok).

**Comment by fraserpal** [comment]
same problem here

**Comment by robgf** [comment]
I have had luck just ignoring the certificates:
git config --global http.sslVerify  false

**Comment by thomaseyde** [comment]
@robgf, that did the trick for me. I dropped `--global` in the hope that this change only affects this one repository. But this solution was unbelievable hard to find!
