### ISSUE TITLE
Unable to push (not a duplicate)

### ISSUE THREAD

**Issue by forcemagic** [atom/github#906]
### Prerequisites

Have a Git repository with a credential that needs a password

### Description

Unable to push to a password-protected repository. Atom asks for my password, but it would not push.

### Steps to Reproduce

1. Click on Git Push

**Expected behavior:**

Push completes successfully. (It works with `git push` from command line)

**Actual behavior:**

I get this: (with debug logging enabled)

```
git-credential-atom: working directory = /var/www/html/phplib
git-credential-atom: socket path = /tmp/github-11755-17965-wizo5v.pzlrllerk9/helper.sock
git-credential-atom: action = get
git-credential-atom: parsed from stdin: [protocol] = [https]
git-credential-atom: parsed from stdin: [host] = [<gitlab url>]
git-credential-atom: parsed from stdin: [username] = [forcemagic]
git-credential-atom: all input received: EOF from stdin
git-credential-atom: discover credential helpers from system git configuration
git-credential-atom: PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
git-credential-atom: failed to list credential helpers. this is ok
Error: Command failed: git config --system --get-all credential.helper

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket. (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
git-credential-atom: attempting to run fill with user-configured credential helpers
git-credential-atom: GIT_ASKPASS = 
git-credential-atom: SSH_ASKPASS = 
git-credential-atom: arguments = credential fill
git-credential-atom: stdin =
protocol=https
host=<gitlab url>
username=forcemagic


git-credential-atom: stdout:

git-credential-atom: stderr:
08:09:21.144397 git.c:371               trace: built-in: git 'credential' 'fill'
fatal: could not read Password for 'https://forcemagic@<gitlab url>': terminal prompts disabled

git-credential-atom: user-configured credential helpers failed with exit code 128. this is ok
git-credential-atom: requesting dialog through Atom socket
git-credential-atom: prompt = "Please enter your credentials for https://forcemagic@<gitlab url>"
                     includeUsername = false
git-credential-atom: connection established
git-credential-atom: writing payload
git-credential-atom: payload written
git-credential-atom: Atom socket stream terminated
git-credential-atom: Atom reply parsed
git-credential-atom: success
08:10:31.894263 run-command.c:369       trace: run_command: '/tmp/github-11755-17965-wizo5v.pzlrllerk9/git-credential-atom.sh erase'
08:10:31.894835 run-command.c:228       trace: exec: '/bin/sh' '-c' '/tmp/github-11755-17965-wizo5v.pzlrllerk9/git-credential-atom.sh erase' '/tmp/github-11755-17965-wizo5v.pzlrllerk9/git-credential-atom.sh erase'
git-credential-atom: working directory = /var/www/html/phplib
git-credential-atom: socket path = /tmp/github-11755-17965-wizo5v.pzlrllerk9/helper.sock
git-credential-atom: action = erase
git-credential-atom: parsed from stdin: [protocol] = [https]
git-credential-atom: parsed from stdin: [host] = [<gitlab url>]
git-credential-atom: parsed from stdin: [username] = []
git-credential-atom: parsed from stdin: [password] = [******]
git-credential-atom: all input received: EOF from stdin
git-credential-atom: discover credential helpers from system git configuration
git-credential-atom: PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
git-credential-atom: failed to list credential helpers. this is ok
Error: Command failed: git config --system --get-all credential.helper

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket. (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
git-credential-atom: attempting to run reject with user-configured credential helpers
git-credential-atom: GIT_ASKPASS = 
git-credential-atom: SSH_ASKPASS = 
git-credential-atom: arguments = credential reject
git-credential-atom: stdin =
protocol=https
host=<gitlab url>
username=
password=*******


remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://forcemagic@<gitlab url>/forcemagic/phplib.git/'
```

**Reproduces how often:**

It always happens when you try to push.

### Versions

- OS: debian jessie
- Atom version:
```
Atom    : 1.18.0-beta2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
- git version `2.1.4`

### Additional Information

I have mentioned this issue on Slack, and it turns out that the credentials are not carried, because they are contained in the url `forcemagic@blabla.com...`. I'm not entirely sure what happens in the background, I can only assume that this is happening.

**Comment by rsese** [comment]
Thanks for the update @forcemagic, I wonder if this was fixed by https://github.com/atom/github/pull/1065?  In any case, I'm glad things are working for you again :v:
