### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPaneItem' of undefined

### ISSUE THREAD

**Issue by tizmagik** [atom/github#934]
I just updated to Atom 1.18 but the Diff View does not show up. I'm guessing it has something to do with a plugin or something I have, but not sure which...

1. Select a file in Git pane with changes (unstaged)
2. CMD+Shift+P then select `GitHub: Focus Diff View`

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getPaneItem' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:783

TypeError: Cannot read property 'getPaneItem' of undefined
    at RootController.focusFilePatchView (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:783:52)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:07.8.0 command-palette:toggle (div.github-StagingView.unstaged-changes-focused)
     -0:04.4.0 core:confirm (input.hidden-input)
     -0:04.4.0 github:focus-diff-view (div.github-StagingView.unstaged-changes-focused)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.1 
atomic-chrome 0.3.0 
busy-signal 1.4.3 
flow-ide 1.5.0 
graphql-autocomplete 1.0.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.65.2 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.4 
linter-eslint 8.2.1 
linter-ui-default 1.6.1 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-autohide 0.10.1 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
platformio-ide-terminal 2.5.1 
prettier-atom 0.33.0 
release-notes 0.53.0 
revert-buffer 0.5.0 
set-syntax 0.3.2 
seti-icons 1.5.3 
smart-tab-name 1.0.5 
smart-tags 0.1.5 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.2 
synced-sidebar 0.4.3 
tab-smart-sort 0.3.0 
tidy-tabs 0.4.0 
```

**Comment by tizmagik** [comment]
I tried again after running `atom --clear-window-state` but the error still happens consistently every time.

**Comment by rsese** [comment]
Thanks for the report!

> I'm guessing it has something to do with a plugin or something I have

Can you try to reproduce in safe mode (`atom --safe`) to confirm?

**Comment by tizmagik** [comment]
@rsese yes, I am able to see the diff view once I run in safe mode. So I guess it is a conflict with a plugin I have? What's a good way to narrow that down? One by one?

**Comment by tizmagik** [comment]
I think I narrowed it down to `tab-smart-sort`

**Comment by rsese** [comment]
Nice!  Thanks for letting us know which package was the issue and for cross-referencing the existing issue there.  It may be that there is still a bug in Atom and if so, we'll need the `tab-smart-sort` maintainer to help track that down so they can either fix the problem or tell us where the problem is coming from. 

Thanks again :v:
