### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isChanged' of undefined

### ISSUE THREAD

**Issue by huvber** [atom/github#967]
[Enter steps to reproduce:]

1. unstage one line of code

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'isChanged' of undefined

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:280889

TypeError: Cannot read property 'isChanged' of undefined
    at Object.isItemSelectable (/opt/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:32:109)
    at ListSelection.isItemSelectable (/opt/atom/resources/app/node_modules/github/lib/views/list-selection.js:80:31)
    at ListSelection.getSelectedItems (/opt/atom/resources/app/node_modules/github/lib/views/list-selection.js:278:24)
    at FilePatchSelection.getSelectedLines (/opt/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:331:40)
    at FilePatchSelection.getSelectedHunks (/opt/atom/resources/app/node_modules/github/lib/views/file-patch-selection.js:259:40)
    at FilePatchView.render (/opt/atom/resources/app/node_modules/github/lib/views/file-patch-view.js:112:54)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:798:36)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:821:38)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:745:42)
    at ReactCompositeComponentWrapper._performComponentUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:723:16)
    at ReactCompositeComponentWrapper.updateComponent (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:644:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/opt/atom/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:560:18)
    at Object.performUpdateIfNecessary (/opt/atom/resources/app/node_modules/react-dom/lib/ReactReconciler.js:156:28)
    at runBatchedUpdates (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:150:27)
    at ReactReconcileTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at ReactUpdatesFlushTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at ReactUpdatesFlushTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:89:38)
    at Object.flushBatchedUpdates (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:172:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:209:31)
    at ReactDefaultBatchingStrategyTransaction.perform (/opt/atom/resources/app/node_modules/react-dom/lib/Transaction.js:156:22)
    at Object.batchedUpdates (/opt/atom/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.enqueueUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:200:28)
    at enqueueUpdate (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:24:22)
    at Object.enqueueSetState (/opt/atom/resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:218:11)
    at FilePatchView.ReactComponent.setState (/opt/atom/resources/app/node_modules/react/lib/ReactBaseClasses.js:64:22)
    at FilePatchView.mouseup (/opt/atom/resources/app/node_modules/github/lib/views/file-patch-view.js:379:16)
```

### Commands

```
     -7:46.1.0 core:move-right (input.hidden-input)
     -7:43.3.0 editor:newline (input.hidden-input)
 12x -7:42.6.0 core:move-right (input.hidden-input)
     -7:40.9.0 core:move-up (input.hidden-input)
     -7:39.9.0 core:undo (input.hidden-input)
     -7:38.2.0 core:move-left (input.hidden-input)
     -6:52.8.0 editor:consolidate-selections (input.hidden-input)
     -6:52.8.0 core:cancel (input.hidden-input)
     -5:47.1.0 core:move-right (input.hidden-input)
     -5:46.2.0 core:move-left (input.hidden-input)
  7x -4:00.3.0 core:move-right (input.hidden-input)
  5x -3:58.8.0 core:backspace (input.hidden-input)
 13x -3:55.4.0 core:move-right (input.hidden-input)
     -3:54 core:backspace (input.hidden-input)
     -3:51.8.0 core:save (input.hidden-input)
     -0:33.4.0 core:confirm (span.)
```

### Non-Core Packages

```
file-icons 2.1.7 
git-plus 7.9.3 
highlight-selected 0.13.1 
language-babel 2.66.0 
minimap 4.28.2 
pigments 0.39.1 
```

**Comment by mattvanhorn** [comment]
I get this when I (un)stage one section of any size, and then try to (un)stage another.

**Comment by BinaryMuse** [comment]
The stack is slightly different, but this appears to be a dup of https://github.com/atom/github/issues/885
