### ISSUE TITLE
Uncaught error when closing “Unstaged Changes” panes

### ISSUE THREAD

**Issue by j-f1** [atom/github#968]
1. Double-click on a file to stage it.
2. Close the resulting changes pane

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

<details><summary>Stack Trace</summary>

Uncaught TypeError: Cannot read property 'getHostNode' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:63

TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:63:34)
    at ReactCompositeComponentWrapper.getHostNode (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:384:34)
    at Object.getHostNode (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:63:35)
    at Object.updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:129:52)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:213:34)
    at ReactDOMComponent._updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:312:37)
    at ReactDOMComponent.updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:299:18)
    at ReactDOMComponent._updateDOMChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:936:18)
    at ReactDOMComponent.updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:754:16)
    at ReactDOMComponent.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:716:16)
    at Object.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:547:16)
    at Object.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at Object.updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:109:31)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:213:34)
    at ReactDOMComponent._updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:312:37)
    at ReactDOMComponent.updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:299:18)
    at ReactDOMComponent._updateDOMChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:936:18)
    at ReactDOMComponent.updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:754:16)
    at ReactDOMComponent.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:716:16)
    at Object.receiveComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:125:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:754:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:724:16)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:645:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:561:18)
    at Object.performUpdateIfNecessary (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:157:28)
    at runBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:150:27)
    at ReactReconcileTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at ReactUpdatesFlushTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:89:38)
    at Object.flushBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:172:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:206:31)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:153:22)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:200:28)
    at enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:24:22)
    at Object.enqueueSetState (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdateQueue.js:219:11)
    at RootController.ReactComponent.setState (/Applications/Atom.app/Contents/Resources/app/node_modules/react/lib/ReactComponent.js:63:22)
    at Object.onDidCloseItem (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:484:24)
    at subscriptions.props.workspace.onDidDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/views/pane-item.js:90:26)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:275:24)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:621:22)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:685:22)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:662:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1696:48)
    at atom-workspace.core:close (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

</details>
<details><summary>Commands</summary>

```
     -5:06.9.0 settings-view:open (input.hidden-input)
  2x -5:02.5.0 core:backspace (input.hidden-input)
     -5:01.4.0 core:confirm (input.hidden-input)
     -4:29.7.0 core:close (table.package-keymap-table.table.native-key-bindings.text)
     -4:25 pane:show-next-item (input.hidden-input)
     -4:21.2.0 core:paste (input.hidden-input)
     -4:19.7.0 core:undo (input.hidden-input)
     -4:16.6.0 editor:newline (input.hidden-input)
     -4:16.2.0 core:paste (input.hidden-input)
  4x -4:07.3.0 core:move-right (input.hidden-input)
  2x -4:06.7.0 intentions:highlight (input.hidden-input)
 11x -4:06.5.0 editor:select-to-end-of-word (input.hidden-input)
     -4:02.8.0 core:save (input.hidden-input)
     -4:01.9.0 core:close (input.hidden-input)
     -3:24.5.0 pane:show-next-item (input.hidden-input)
  2x -1:53.8.0 core:close (div.github-FilePatchView.is-unstaged)
```

</details>
<details><summary>Non-Core Packages</summary>

```
aligner 1.2.2 
aligner-javascript 1.1.0 
aligner-python 1.1.0 
allcontributors 1.1.0 
atom-easy-jsdoc 4.12.1 
atom-jest-snippets 1.1.1 
atom-live-server 2.1.2 
atom-minify 0.8.0 
atom-react-autocomplete 0.1.10 
atom-typescript 11.0.3 
auto-copyright 0.5.0 
autocomplete-emojis 2.5.0 
autocomplete-modules 1.6.10 
autocomplete-python 1.9.0 
bottom-dock 0.4.4 
build 0.68.0 
build-gulp 0.11.0 
busy 0.7.0 
busy-signal 1.4.3 
cdnjs 1.5.5 
character-table 0.4.3 
color-picker 2.2.5 
css-specificity 0.2.2 
devdocs 0.2.1 
diff-pane 0.3.0 
django-templates 0.5.0 
docs-snippets 0.8.0 
double-tag 0.8.0 
drag-relative-path 1.1.2 
editor-stats 0.17.0 
editorconfig 2.2.2 
emmet 2.4.3 
export-html 3.1.0 
expose 0.12.2 
file-icons 2.1.7 
file-type-icons 1.3.4 
file-watcher 1.1.0 
filesize 3.0.0 
git-plus 7.9.3 
git-status 0.3.4 
git-time-machine 1.5.9 
gitignores 0.2.0 
highlight-bad-chars 1.0.7 
highlight-selected 0.13.1 
hyperclick 0.0.40 
hyperlink-hyperclick 1.3.4 
intentions 1.1.2 
intentions-numbers 1.0.4 
ios 0.1.0 
iso8601-timestamp 0.1.1 
js-hyperclick 1.11.0 
jsdoc-generator 0.2.3 
jumpy 3.1.3 
language-apache 1.7.0 
language-appcache 0.1.1 
language-babel 2.66.0 
language-gitignore 0.3.0 
language-jade 0.7.2 
language-json-comments 0.16.3 
language-liquid 0.6.0 
language-svg 0.9.2 
linter 2.2.0 
linter-alex 4.0.0 
linter-erb 1.1.0 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-js-standard 3.9.1 
linter-rubocop 2.1.1 
linter-tslint 1.6.0 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
linter-xo 0.23.1 
MagicPython 1.0.10 
markdown-preview-plus 2.4.9 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-titles 1.11.0 
native-ui 0.21.0 
no-title-bar 0.6.6 
on-save 2.0.1 
open-recent 5.0.0 
package-reloader 1.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
prettier-atom 0.34.0 
python-jedi 0.3.8 
sloc 1.1.0 
split-diff 1.4.2 
standardjs-snippets 2.6.0 
status-display 0.0.0 
svg-preview 0.11.0 
tester 1.3.1 
tester-jest 1.1.6 
todo-manager 0.2.10 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tool-bar-main 0.0.10 
tree-view-autoresize 2.1.0 
tree-view-filter 0.5.3 
tree-view-git-branch 0.1.2 
true-xcode-syntax 0.2.0 
turbo-javascript 1.4.0 
underline-trailing-whitespace 1.4.2 
unicode-input 0.5.1 
word-jumper-deluxe 1.3.0 
xcode-theme 1.4.0 
Zen 0.18.0 
```

</details>

**Comment by rsese** [comment]
Thanks for the report!  I wasn't able to reproduce so just to confirm, is the error reproducible for you?  If so, can you also reproduce in safe mode (`atom --safe`)?

**Comment by j-f1** [comment]
Thanks for getting back to me! I can no longer reproduce it in normal (non-safe) mode.
