### ISSUE TITLE
New features that comes with atom v1.18 do not appear

### ISSUE THREAD

**Issue by sultan99** [atom/github#975]
I have installed a new version of atom 1.18.0 in hope to get the new features: [https://github.atom.io/](url)
But my status bar is still like it was before: 
![image](https://user-images.githubusercontent.com/2598056/27466693-49011020-57fe-11e7-878e-747f1f56c2ba.png)

I have uninstalled the previous version and removed all `atom` folders in **\\AppData\\** and tried several times to reinstall atom but no success.

I'm using Windows 10 and the `apm -v`:
- apm  1.18.1
- npm  3.10.10
- node 6.9.5 x64
- python 2.7.13
- git 2.10.2.windows.1
- visual studio

Atom version:
![image](https://user-images.githubusercontent.com/2598056/27466786-e90db91a-57fe-11e7-94e9-5641fa758b01.png)

What have I done wrong?

**Comment by serafeimgr** [comment]
Open up Command Palette and search for Github: Toggle Git Tab

**Comment by sultan99** [comment]
![image](https://user-images.githubusercontent.com/2598056/27479578-48bfdeec-5836-11e7-90b6-65613ff78155.png)
Nothing like `Github: Toogle Git  Tab` in my **Command Palette (ctrl+shift+p)**

**Comment by serafeimgr** [comment]
Is `github` package enabled?

**Comment by sultan99** [comment]
![image](https://user-images.githubusercontent.com/2598056/27493496-e23abb0c-586b-11e7-8ea4-5453c54a395c.png)
No, it is enabled. It is the first thing I have checked when tried to solve the problem.

**Comment by Arcanemagus** [comment]
If you launch Atom in safe mode (`atom --safe`) does it show up? It's possible that something else is removing it.

**Comment by johnwebbcole** [comment]
`atom --safe` still doesn't work.  Tired Atom 1.18.1 and downgraded to 1.18.0 also.  In the console the following error appears:

```
<embedded>:69654 Error serializing package 'github' TypeError: Cannot read property 'serialize' of undefined
    at GithubPackage.serialize (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\github-package.js:268:43)
    at Package.module.exports.Package.serialize (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:785:103)
    at PackageManager.module.exports.PackageManager.serializePackage (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:712:69)
    at PackageManager.module.exports.PackageManager.serialize (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:705:20)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:880:44)
    at C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:1194:33
    at AtomEnvironment.module.exports.AtomEnvironment.saveState (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:1190:20)
    at C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:370:34
```

There are several new issues with this error.

My system: Windows 10
```
apm -v
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.1.windows.2
visual studio 2015
```

**Comment by BinaryMuse** [comment]
@johnwebbcole Thanks for the stack — this looks like a dup of https://github.com/atom/github/issues/979

@sultan99 Do you see the same error in the console?

**Comment by sultan99** [comment]
@BinaryMuse I get the same error as @johnwebbcole :
`<embedded>:69654 Error serializing package 'github' TypeError: Cannot read property 'serialize' of undefined
    at GithubPackage.serialize (C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\github-package.js:268:43)
    at Package.module.exports.Package.serialize (C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:785:103)
    at PackageManager.module.exports.PackageManager.serializePackage (C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:712:69)
    at PackageManager.module.exports.PackageManager.serialize (C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:705:20)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:880:44)
    at C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:1194:33
    at AtomEnvironment.module.exports.AtomEnvironment.saveState (C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:1190:20)
    at C:\Users\sarziyev\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:370:34`

**Comment by johnwebbcole** [comment]
A workaround in #833 seems to work here too.  Start with `NODE_ENV="production" atom .` and the github panel appears and works.

**Comment by BinaryMuse** [comment]
Okay, this seems to be a dup of #833. Thanks :bowing_woman:
