### ISSUE TITLE
Error serializing package 'github' when attempting to open Git tab

### ISSUE THREAD

**Issue by absynce** [atom/github#979]
### Prerequisites

* ✔️ Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
  ⚠️ Yes, but it has the same error.
* ✔️ Have you followed all applicable steps in the [debugging guide][debugging-guide]?
  * ✔️ Clear saved state
  ⚠️ Same error.
  * ✔️ Reset to Factory Defaults
  ⚠️ Same error.
* ✔️ Have you checked the FAQs on the [message board][message-board] for common solutions?
* ✔️ Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When trying to open the Git tab it fails and logs an error to the console:
```
<embedded>:69654 Error serializing package 'github' TypeError: Cannot read property 'serialize' of undefined
    at GithubPackage.serialize (C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\github-package.js:268:43)
    at Package.module.exports.Package.serialize (C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:785:103)
    at PackageManager.module.exports.PackageManager.serializePackage (C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:712:69)
    at PackageManager.module.exports.PackageManager.serialize (C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:705:20)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:880:44)
    at C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:1194:33
    at AtomEnvironment.module.exports.AtomEnvironment.saveState (C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:1190:20)
    at C:\Users\JSmith\AppData\Local\atom\app-1.18.0\resources\app\src\atom-environment.js:370:34module.exports.Package.serialize @ <embedded>:69654module.exports.PackageManager.serializePackage @ <embedded>:20604module.exports.PackageManager.serialize @ <embedded>:20597module.exports.AtomEnvironment.serialize @ <embedded>:1114(anonymous function) @ <embedded>:1428module.exports.AtomEnvironment.saveState @ <embedded>:1424(anonymous function) @ <embedded>:604
```

### Steps to Reproduce

1. Open Atom in a folder with a Git repo.
2. Try to open the Git tab: Ctrl+Shift+9.
3. 😢 

**Expected behavior:**

The Git tab should open.

**Actual behavior:**

An error occurred. See the description.

**Reproduces how often:**

💯It fails 100% of the time I try to open it.

### Versions

```
λ atom --version

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
```
λ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 ia32
python
git 2.10.0.windows.1
visual studio 2015
```

#### Package
```
github 0.3.3
```

#### OS

|Key| Value |
| ---      | ---       |
|OS Name	| **Microsoft Windows 10 Pro** |
|Version	| **10.0.15063 Build 15063** |

### Additional Information

This worked for several days. It just stopped today but I'm on the same version of Atom. 

I'm loving the feature. Especially the diff and individual file staging. It was easy to incorporate into my workflow.

**Comment by BinaryMuse** [comment]
Looks like `GithubPackage#serialize` calls `this.controller.serialize` unconditionally when serializing, but technically there's no guarantee that the controller property is set (as it's set via ref callback on the `RootController`). Not sure why we're serializing before we get an initial render, but definitely worth guarding against.

**Comment by BinaryMuse** [comment]
Also @absynce, thank you for the most excellent bug report! :bowing_woman:

**Comment by johnwebbcole** [comment]
A workaround seems to be in #833 If you start with `NODE_ENV="production" atom .`

**Comment by baldurh** [comment]
When I first opened Atom 1.18 the Git and GitHub tabs were open and I could log in and everything was fine. Then I closed both tabs and now I cannot open neither of them again because of this error. The workaround posted by @johnwebbcole worked for me. I’m running on a mac.

**Comment by DavideDaniel** [comment]
confirmed - I'm running on a mac -- I updated packages last night, manually deleted 1 package that was causing all other updates to not run, and following that tabs disappeared. Now when I need to see github tabs, I need to run with `NODE_ENV=production atom .`

**Comment by johnwebbcole** [comment]
I discovered that my windows system had a user ENV setting `NODE_ENV=development`.  I deleted that using the control panel and I do not need to set now.

I don't know what set that user ENV.

**Comment by BinaryMuse** [comment]
Okay, these all seem to be NODE_ENV related, so this is a dup of #833
