### ISSUE TITLE
Uncaught TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by ashtonbradley** [atom/github#981]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: "Red Hat
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'update' of undefined

```
At /usr/share/atom-beta/resources/app/node_modules/github/node_modules/etch/lib/patch.js:52

TypeError: Cannot read property 'update' of undefined
    at updateComponent (/usr/share/atom-beta/resources/app/node_modules/github/node_modules/etch/lib/patch.js:52:18)
    at patch (/usr/share/atom-beta/resources/app/node_modules/github/node_modules/etch/lib/patch.js:16:25)
    at updateSync (/usr/share/atom-beta/resources/app/node_modules/github/node_modules/etch/lib/component-helpers.js:108:26)
    at /usr/share/atom-beta/resources/app/node_modules/github/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (/usr/share/atom-beta/resources/app/node_modules/github/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report @ashtonbradley!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (`atom --safe`)?

@Bjoernsen - is the error error reproducible for you?  Also, do you see it with any project or just a particular Rails project?

**Comment by Bjoernsen** [comment]
@rsese this error appears every time. There is no different using the safe mode.

I also tried to open a project that only includes a `Dockerfile` and a `.gitlab-ci.yml` file.

I had the idea that it might be because I use GitLab repos. Therefore I cloned boths: https://gitlab.com/gitlab-org/gitlab-shell and https://github.com/gitlabhq/gitlab-shell. Unfortunately, I receive this error for boths repos. So I think GitLab is not a issue.
